### ISSUE TITLE
aggiungere OVERLAY come blending mode

### ISSUE THREAD

**Issue by bardo78** [gRally/dev#113]
http://www.slrlounge.com/school/photoshop-blend-modes/
"When using the Overlay Blend Modes anything darker than 50% Grey will darken and add contrast to the underlying image and anything brighter than 50% Grey will brighten and add contrast to the underlying image. This is one of our most frequently used Blend Modes"

Aggiungo
http://en.wikipedia.org/wiki/Blend_modes#Overlay

**Comment by ghiboz** [comment]
vecchia roba di **OGRE**
