### ISSUE TITLE
gTrackEditor - CloudsScale

### ISSUE THREAD

**Issue by Gundam99** [gRally/dev#132]
Mettendo lo slider a posizione minima (-0,00190) e a posizione massima (0,00190) va in errore
Se non si mette il valore minimo o il valore massimo, funziona correttamente

![image](https://cloud.githubusercontent.com/assets/8404030/4552060/c5e789d2-4e7b-11e4-8653-9a56606f3a72.png)

**Comment by ghiboz** [comment]
era relativo a SkyX, ora non c'è più
