### ISSUE TITLE
Plugin export

### ISSUE THREAD

**Issue by Gundam99** [gRally/dev#134]
Il layout non prende le textures del suo graphics.mat (l'editor visualizza l'oggetto senza texture)

Per far prendere le textures, vanno copiati i **materiali del graphics.mat del layout** nel **graphics.mat del main** (ovviamente vanno copiati solo i materiali non presenti nel graphics.mat del main)

Nel graphics.mat del layout trovo :
```
diffuseMap textures/con_met_01_d.dds
normalMap textures/con_met_01_n.dds
specMap textures/con_met_01_s.dds
```
E' un problema di puntamento alla cartella textures ?

**Comment by ghiboz** [comment]
ora funziona ![](http://i.imgur.com/ev1n3US.png)
