### ISSUE TITLE
Ombre, blinkano se ti allontani da 0,0,0

### ISSUE THREAD

**Issue by ghiboz** [gRally/dev#137]
Con la BB ho notato che le ombre all'inizio *(vicino allo 0,0,0 che se non erro è sulla partenza o cmq li vicino)* sono molto stabili, mentre se ti allontani blinkano sempre più forte.

**Comment by bardo78** [comment]
Anche le decals sembrano soffrire di questo problema di Z-fighting.
Non so se può essere d'aiuto
http://www.ogre3d.org/forums/viewtopic.php?f=2&t=47733

**Comment by ghiboz** [comment]
@bardo78 prova a modificare il **render.ini** mettendo near distance 1 e view distance 100
ti vedrai il cruscotto solo da 1 metro in poi, ma se il problema è lo z-fighting così dovrebbe scomparire, se invece rimane, non è quello :(

**Comment by bardo78** [comment]
test effettuato.
ora il bias dell'ombra è fantastico e tiene lungo tutta la prova.
Ci sono piccoli sfarfallamenti in alcuni punti.
Però è tutto più preciso.

**Comment by ghiboz** [comment]
quindi abbiamo il problema dello z-buffer

**Comment by bardo78** [comment]
prima di sputare una sentenza chiederei anche a @Gundam99 di fare un test...
però l'impressione è quella...cioè per farti un esempio...ora le ombre dove ci sono i pali di sostegno del guardrail o della segnaletica partono perfettamente dove c'è l'incontro del palo con le altre superfici.

**Comment by ghiboz** [comment]
ok, ma non hai cambiato il shadowvbias dentro shadowsmw.h, solo near e far distance giusto?

**Comment by bardo78** [comment]
Cambiato solo quello che mi hai detto dentro al render.ini

**Comment by Gundam99** [comment]
in common\shadowsmw.h, a livello di bias c'è solo questo valore : #define FIXED_BIAS 0.0000025

**Comment by ghiboz** [comment]
passaggio a Unity
