### ISSUE TITLE
Modificare i valori di Ambient,Diffuse e Specular della luce solare.

### ISSUE THREAD

**Issue by bardo78** [gRally/dev#145]
Verificare valori con ultimi trovati e salvati nella cartella D:\gRally_Sviluppo\GoogleDrive\test_regolazione_luce_ambientale

I file di riferimento sono:
valori_141227_alba.jpg
valori_141227_mezzogiorno.jpg

**Comment by ghiboz** [comment]
guarda un po': non era questa?
https://github.com/gRally/dev/issues/140

**Comment by bardo78** [comment]
Ecco i valori per il mattino all'alba/tramonto 
![valori_150103_mattino](https://cloud.githubusercontent.com/assets/7723541/5603993/4b083f3e-93a1-11e4-84a6-141584ac72d3.jpg)

e per il mezzogiorno (l'ora che vedi è le 13, ho messo l'orario in cui il sole era più verticale possibile)

![valori_150103_mezzogiorno](https://cloud.githubusercontent.com/assets/7723541/5603994/55078094-93a1-11e4-8d55-e15e464a6cc4.jpg)
