### ISSUE TITLE
Valori di Ambient, Diffuse e Speculare della luce solare bloccati

### ISSUE THREAD

**Issue by bardo78** [gRally/dev#152]
Se si prova a cambiare i valori in oggetto, l'editor continua ad usare i valori di partenza.
Si vedono dei "flash" che evidenza che la luice cambia colore ma poi tutto torna ai valori iniziali preimpostati.

**Comment by ghiboz** [comment]
si, li ho hardcodati nel codice, ti metto fuori sia i 2 gradi e i 6 colori
