### ISSUE TITLE
Diffuse map e Opacity map diverse = non funziona l'alpha channel

### ISSUE THREAD

**Issue by bardo78** [gRally/dev#153]
ho due mappe diverse: una mappa sul diffuse e una mappa sull'opacity.
la mappa sul diffuse può avere o meno un canale alpha (non cambia la situazione), la mappa dell'opacity ha un canale alpha.
risultato: viene ignorato il canale alpha della mappa che carico nello slot dell'opacity.

scopo di questo setup dei materiali: riutilizzare delle texture già caricate e lavorare con una mappa di trasparenza che può avere risoluzioni più basse di quella della diffusione risparmiando così memoria video.

info aggiuntive: il problema si ha sia usando lo stesso UVchannel che cambiandolo. In ogni caso la verifica sul funzionamento va fatta considerando l'opzione di usare UVchannel diversi.
Il problema si è verificato sia con materiale standard che "decals".

**Comment by ghiboz** [comment]
ogre
