### ISSUE TITLE
Impossibile visualizzare erba custom richiamando lo shader grsGrass_

### ISSUE THREAD

**Issue by bardo78** [gRally/dev#156]
Richiamando lo shader grsGrass_ per avere un'erba custom con tanto di movimento, quest'ultima non viene visualizzata.

Non capisco se non riesce a trovare il percorso della texture o se c'è qualche altro problema

**Comment by ghiboz** [comment]
allora, sto provando, e con questo materiale qui funziona tutto bene:

```
material grmTest
{
	parent grsGrass_
	vertex_colour false
	diffuseMap red.png
}
```

io ho fatto un file grass.mat nella cartella del tracciato, ci ho messo questo dentro, come *diffuseMap* ho solo messo red.png perchè è una tex 'standard', se metti una tex all'interno di `textures` dovrai, come nel graphics.mat mettere `diffuseMap textures/nomeTexture.dds`

**Comment by bardo78** [comment]
Funziona! :)
Ottimo. Grazie
E' possibile associare anche una normal map?
Io ho provato scrivendo

material grmTest
{
    parent grsGrass_
    vertex_colour false
    diffuseMap textures/nomediffuse.dds
    normalMap textures/nomenormal.dds
}

Ma senza risultati apprezzabilmente diversi.
