### ISSUE TITLE
Bug grafici e 3D

### ISSUE THREAD

**Issue by GRally-mulder** [gRally/dev#159]
![shot_20150312_224638](https://cloud.githubusercontent.com/assets/8559142/6629826/80f4d8a4-c912-11e4-807f-565dfa741ff6.jpg)
![shot_20150312_225136](https://cloud.githubusercontent.com/assets/8559142/6629828/80fdd684-c912-11e4-900a-37caf24939d2.jpg)
![shot_20150312_225255](https://cloud.githubusercontent.com/assets/8559142/6629827/80f9aa64-c912-11e4-886b-32bdc1f206d8.jpg)
![shot_20150312_225641](https://cloud.githubusercontent.com/assets/8559142/6629829/81023dbe-c912-11e4-8faa-1e862278e704.jpg)
![shot_20150312_230047](https://cloud.githubusercontent.com/assets/8559142/6629830/810616f0-c912-11e4-8976-2eadde770965.jpg)
![shot_20150312_230234](https://cloud.githubusercontent.com/assets/8559142/6629831/8109f07c-c912-11e4-9b42-67133d84c53a.jpg)
![shot_20150312_230517](https://cloud.githubusercontent.com/assets/8559142/6629832/81104576-c912-11e4-8689-7f118ae9e7e1.jpg)
![shot_20150312_230726](https://cloud.githubusercontent.com/assets/8559142/6629833/8119a382-c912-11e4-83fa-8a89592fad68.jpg)
![shot_20150312_230834](https://cloud.githubusercontent.com/assets/8559142/6629834/811dc048-c912-11e4-8c8d-31df6295f497.jpg)
![shot_20150312_230932](https://cloud.githubusercontent.com/assets/8559142/6629835/8123d62c-c912-11e4-9a8c-f6ac336d57ad.jpg)
![shot_20150312_231055](https://cloud.githubusercontent.com/assets/8559142/6629836/81283794-c912-11e4-8994-53401a7ae923.jpg)
![shot_20150312_231146](https://cloud.githubusercontent.com/assets/8559142/6629837/812ee2d8-c912-11e4-825b-33db72249ef9.jpg)
![shot_20150312_231600](https://cloud.githubusercontent.com/assets/8559142/6629838/813350ca-c912-11e4-8790-b5aa48f37da0.jpg)

**Comment by Gundam99** [comment]
Molti sono già a posto, comunque è un ottimo promemoria per i controlli

**Comment by Gundam99** [comment]
Ora dovrebbero essere tutti a posto
