### ISSUE TITLE
Creare il mod Baitoni Bondone

### ISSUE THREAD

**Issue by ghiboz** [gRally/dev#161]
visto che il primo maggio è alle porte, sarebbe bello iniziare a testare la bb in maniera completa, fino ad ora, tra copie su copy, zip via mail, ecc.. è un bel casino, e visto tipo @GRally-mulder che quando ha provato, ha segnato delle anomalie, ma quasi tutte già sistemate nella versione 'giusta'...

io terrei le versioni su copy, ecc.. per provare cose particolari, ma farei il mod (così si prova anche se funziona :lollipop: )

la guida è qui: https://github.com/gRally/dev/wiki/Mods

**Comment by Gundam99** [comment]
Mod creato con versione 1.0 (rail **senza** materiale 2sided) e update 1.1 (rail **con** materiale 2sided)

Mi sa che va creato un issue gMods per segnalare eventuali bugs/implementazioni

Per ora lo segnalo qui : **bug update**
- installazione 1.0 (full) **OK**
- installazione 1.1 (update), crea la cartella su disco **C:**

esempio : 
ho gRally installato in **E**:\gRally_ALPHA
eseguo il setup della 1.0 e installa in **E**:\gRally_ALPHA\data\Tracks\baitoni_bondone-0.1.0
eseguo gMods->Update e installa in **C**:\gRally_ALPHA\data\Tracks\baitoni_bondone-0.1.1

se sposto la cartella della 1.1 in data\tracks funziona alla perfezione

**Comment by Gundam99** [comment]
meglio non chiudere fino a quando non si risolve il discorso update->disco :)

**Comment by ghiboz** [comment]
ma domanda: quando esegui `gMods->Update`, il gMods.exe dove è? perchè io prendo il percorso dell'.exe per aggiornare

**Comment by Gundam99** [comment]
è nella cartella gRally :)

**Comment by bardo78** [comment]
stessa cosa per me, ho l'eseguibile dentro a D:\gRally_ALPHA ma l'update me lo ha messo in C:\programmi\gRally_ALPHA\data\Tracks ecc

**Comment by ghiboz** [comment]
prova con questo .exe:

https://files.gitter.im/gRally/dev/DevCorner/ELrh/gMods.rar
