### ISSUE TITLE
verificare ingame la differenza tra pivot 0 e non

### ISSUE THREAD

**Issue by ghiboz** [gRally/dev#162]
da verificare, magari con la BB esportata, soprattutto ingame, ma anche con l'editor, per capire se, dopo tutti questi aggiornamenti, è migliorato qualcosa o meno.

**Comment by bardo78** [comment]
dalle mie prove con l'editor, se metto "pivot 0,0,0" perdo circa il 10% di FPS.

**Comment by ghiboz** [comment]
però poi ingame dici che è al contrario vero?
pivot 0 0 0 guadagno di 5, 10% rispetto al no pivot

confermi @bardo78 ?

**Comment by bardo78** [comment]
confermo che c'è un guadagno ma veramente minimo. non più 10%
Anzi il valore peggiore era sostanzialmente uguale...
