### ISSUE TITLE
Scene pivot scena a 0 0 0  e a 5000 5000 5000 con e senza flag pivot 0 0 0

### ISSUE THREAD

**Issue by Gundam99** [gRally/dev#171]
**gRally Tracks\Plane500x500** file **Plane500x500.rar**
contenente :
1 - cartella **export_0** (export scena con centro a 0 0 0 e **SENZA** flav pivot 0 0 0)
2 - cartella **export_0_pivot_000** (export scena con centro a 0 0 0 e **CON** flav pivot 0 0 0)
3 - cartella **export_5000** (export scena con centro a 5000 5000 5000 e **SENZA** flav pivot 0 0 0)
4 - cartella **export_5000_pivot_000** (export scena con centro a 5000 5000 5000 e **CON** flav pivot 0 0 0)
5 - cartella **maps**
6 - file Plane500_2010_pivot_0.max (per export 1 e 2)
7 - Plane500_2010_pivot_5000.max (per export 3 e 4)

Oggetti scena 
**CENTRO**
![image](https://cloud.githubusercontent.com/assets/8404030/6882377/148463b0-d583-11e4-8555-8d70c4488008.png)

**NORD-OVEST**
![image](https://cloud.githubusercontent.com/assets/8404030/6882381/281daaf8-d583-11e4-9506-683331d91f19.png)

**NORD-EST** (albero di sinistra materiale 2-sided, albero di destra con doppia faccia no materiale 2-sided)
![image](https://cloud.githubusercontent.com/assets/8404030/6882384/351111be-d583-11e4-8c8d-cf9e9cc42fb1.png)

**SUD-EST**
![image](https://cloud.githubusercontent.com/assets/8404030/6882399/6cc09f76-d583-11e4-8b0c-0ef3af396c65.png)

**SUD-OVEST**
![image](https://cloud.githubusercontent.com/assets/8404030/6882401/79bd19de-d583-11e4-9830-1416fa19970b.png)

**Comment by Gundam99** [comment]
**NOTE**
Sembra che l'effetto sia più pronunciato quando il centro della ***scena è distante da 0 0 0 con il flag pivot 000 seezionato***
Ti ho messo i 6 shot (4 normali + i 2 wireframe della 5000 pivot 000) dei casi estremi. 
A occhio, senza flag pivot 0 0 0 "si corregge" più o meno alla stessa distanza indipendentemente dalla posizione della scena (scena centrata a 0 0 0 o scena centrata a 5000 5000 5000)
Con flag pivot e scena centrata a 5000 5000 5000, per avere la vista corretta ti devi avvicinare molto

Scena centro 0 0 0 senza flag pivot 000 : posizione 1
![0_no_pivot000a](https://cloud.githubusercontent.com/assets/8404030/6882408/e398830c-d583-11e4-80aa-8738d7afda30.jpg)

Scena centro 0 0 0 senza flag pivot 000 : posizione 2
![0_no_pivot000b](https://cloud.githubusercontent.com/assets/8404030/6882413/116732ce-d584-11e4-8967-d633ee53e9fa.jpg)

Scena centro 5000 5000 5000 con flag pivot 000: posizione 1
![5000_pivot000a](https://cloud.githubusercontent.com/assets/8404030/6882420/3736b57e-d584-11e4-961e-1ebe1db6c1d1.jpg)
![shot_20150328_200231](https://cloud.githubusercontent.com/assets/8404030/6882453/90c956fe-d585-11e4-95ee-3ec1eb33ae2b.jpg)

Scena centro 5000 5000 5000 con flag pivot 000: posizione 2
![5000_pivot000b](https://cloud.githubusercontent.com/assets/8404030/6882424/42a8f836-d584-11e4-9ae5-cadb347ddd0d.jpg)
![shot_20150328_200236](https://cloud.githubusercontent.com/assets/8404030/6882454/99906124-d585-11e4-8cb8-6c4336394ec2.jpg)

**Comment by ghiboz** [comment]
passaggio a Unity
