### ISSUE TITLE
creare la spline della bb

### ISSUE THREAD

**Issue by ghiboz** [gRally/dev#172]
lo script è qui:
https://github.com/gRally/gTrackEditor/blob/master/3ds%20Max%20scripts/ExportSpline.ms

video:
[![](http://img.youtube.com/vi/ZMgtCg1ymIE/0.jpg)](http://www.youtube.com/watch?v=ZMgtCg1ymIE)

**Comment by Gundam99** [comment]
ricevuto

**Comment by Gundam99** [comment]
in gRally Tracks\Baitoni-Bondone FBX
- **layout0.xml**

La spline è leggermente più corta, è stata troncata in corrispondenza del collision
