### ISSUE TITLE
esportare anche il graphics.mat

### ISSUE THREAD

**Issue by ghiboz** [gRally/dev#173]
visto che i materiali sono complessi: esportare anche con il plugin il file graphics.mat, così posso mappare correttamente

**Comment by Gundam99** [comment]
Devo passarti l'ultima versione del **graphics.mat** generato dall'exporter ?

**Comment by ghiboz** [comment]
si, perché così posso mappare correttamente in unity

Paolo 'ghiboz' Ghibaudo

**Comment by ghiboz** [comment]
vecchia roba di **OGRE**
