### ISSUE TITLE
Show room - livree

### ISSUE THREAD

**Issue by Gundam99** [gRally/dev#185]
Non prende le livree
![image](https://cloud.githubusercontent.com/assets/8404030/7479126/df6c2fdc-f35f-11e4-9189-96494774784c.png)

**Comment by ghiboz** [comment]
con il nuovo rilascio imminente, controllare se il problema persiste, il file **output_log.txt** all'interno di *ShowRoom_Data* le righe:

```
LiveryPath: C:\Users\Administrator\Documents/gRally/Cars/131/Livery\Alitalia.png
LiveryUnityPath: file://C:/Users/Administrator/Documents/gRally/Cars/131/Livery/Alitalia.png
```

**Comment by bardo78** [comment]
a me non funzionano ancora.
Questo il mio log
-----------------------------
Initialize engine version: 5.0.1f1 (5a2e8fe35a68)
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.0]
    Renderer: NVIDIA GeForce GTX 570 (ID=0x1081)
    Vendor:   NVIDIA
    VRAM:     1234 MB
Begin MonoManager ReloadAssembly
Platform assembly: D:\gRally_ALPHA\ShowRoom_Data\Managed\UnityEngine.dll (this message is harmless)
Loading D:\gRally_ALPHA\ShowRoom_Data\Managed\UnityEngine.dll into Unity Child Domain
Platform assembly: D:\gRally_ALPHA\ShowRoom_Data\Managed\Assembly-CSharp-firstpass.dll (this message is harmless)
Loading D:\gRally_ALPHA\ShowRoom_Data\Managed\Assembly-CSharp-firstpass.dll into Unity Child Domain
Platform assembly: D:\gRally_ALPHA\ShowRoom_Data\Managed\Assembly-CSharp.dll (this message is harmless)
Loading D:\gRally_ALPHA\ShowRoom_Data\Managed\Assembly-CSharp.dll into Unity Child Domain
Platform assembly: D:\gRally_ALPHA\ShowRoom_Data\Managed\UnityEngine.UI.dll (this message is harmless)
Loading D:\gRally_ALPHA\ShowRoom_Data\Managed\UnityEngine.UI.dll into Unity Child Domain
Platform assembly: D:\gRally_ALPHA\ShowRoom_Data\Managed\gUtility.dll (this message is harmless)
Loading D:\gRally_ALPHA\ShowRoom_Data\Managed\gUtility.dll into Unity Child Domain
- Completed reload, in  0.365 seconds
<RI> Initializing input.

<RI> Input initialized.

desktop: 1920x1080 60Hz; virtual: 3840x1080 at 0,0
<RI> Initialized touch support.

Platform assembly: D:\gRally_ALPHA\ShowRoom_Data\Managed\System.Core.dll (this message is harmless)
Platform assembly: D:\gRally_ALPHA\ShowRoom_Data\Managed\System.dll (this message is harmless)
HDR and MultisampleAntiAliasing (in Forward Rendering Path) is not supported. This camera will render without HDR buffers. Disable Antialiasing in the Quality settings if you want to use HDR.
 
(Filename:  Line: 2630)

Init Gbz Utility
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebug.gen.cpp Line: 56)

gRallyFolder: D:\gRally_ALPHA/
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebug.gen.cpp Line: 56)

Path: D:\gRally_ALPHA/
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebug.gen.cpp Line: 56)

Setting up 2 worker threads for Enlighten.
  Thread -> id: 16fc -> priority: 1 
  Thread -> id: 1e0c -> priority: 1 
starting www download: file://D:/gRally_ALPHA//Data/Cars/131/car.unity3d
The referenced script on this Behaviour is missing!
 
(Filename:  Line: 1560)

The referenced script on this Behaviour is missing!
 
(Filename:  Line: 1560)

The referenced script on this Behaviour is missing!
 
(Filename:  Line: 1713)

The referenced script on this Behaviour is missing!
 
(Filename:  Line: 1713)

The referenced script on this Behaviour is missing!
 
(Filename:  Line: 1560)

The referenced script on this Behaviour is missing!
 
(Filename:  Line: 1560)

The referenced script on this Behaviour is missing!
 
(Filename:  Line: 1713)

The referenced script on this Behaviour is missing!
 
(Filename:  Line: 1713)

The referenced script on this Behaviour is missing!
 
(Filename:  Line: 1713)

The referenced script on this Behaviour is missing!
 
(Filename:  Line: 1713)

Center: (0.0, 0.4, 1.1), Extents: (0.9, 0.7, 2.1)
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebug.gen.cpp Line: 56)

LiveryPath: C:\Users\Riccardo\Documents/gRally/Cars/131/Livery\Alitalia.png
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebug.gen.cpp Line: 56)

LiveryUnityPath: file://C:/Users/Riccardo/Documents/gRally/Cars/131/Livery/Alitalia.png
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebug.gen.cpp Line: 56)

You are trying to load data from a www stream which had the following error when downloading.
Couldn't open file /Users/Riccardo/Documents/gRally/Cars/131/Livery/Alitalia.png
 
(Filename:  Line: 1076)

LiveryPath: C:\Users\Riccardo\Documents/gRally/Cars/131/Livery\OlioFiat.png
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebug.gen.cpp Line: 56)

LiveryUnityPath: file://C:/Users/Riccardo/Documents/gRally/Cars/131/Livery/OlioFiat.png
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebug.gen.cpp Line: 56)

You are trying to load data from a www stream which had the following error when downloading.
Couldn't open file /Users/Riccardo/Documents/gRally/Cars/131/Livery/OlioFiat.png
 
(Filename:  Line: 1076)

drawLivery True
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebug.gen.cpp Line: 56)

drawLivery True
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebug.gen.cpp Line: 56)

LiveryPath: C:\Users\Riccardo\Documents/gRally/Cars/131/Livery\Alitalia.png
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebug.gen.cpp Line: 56)

LiveryUnityPath: file://C:/Users/Riccardo/Documents/gRally/Cars/131/Livery/Alitalia.png
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebug.gen.cpp Line: 56)

You are trying to load data from a www stream which had the following error when downloading.
Couldn't open file /Users/Riccardo/Documents/gRally/Cars/131/Livery/Alitalia.png
 
(Filename:  Line: 1076)

LiveryPath: C:\Users\Riccardo\Documents/gRally/Cars/131/Livery\OlioFiat.png
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebug.gen.cpp Line: 56)

LiveryUnityPath: file://C:/Users/Riccardo/Documents/gRally/Cars/131/Livery/OlioFiat.png
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebug.gen.cpp Line: 56)

You are trying to load data from a www stream which had the following error when downloading.
Couldn't open file /Users/Riccardo/Documents/gRally/Cars/131/Livery/OlioFiat.png
 
(Filename:  Line: 1076)
