### ISSUE TITLE
Skipad Motorshow: il tempo di gara si interrompe dopo qualche secondo.

### ISSUE THREAD

**Issue by bardo78** [gRally/dev#187]
Non ho ben capito in che momento me lo segna però mi ritrovo con un tempo di 7 secondi...quindi o lo fa subito all'inizio oppure si resetta, si incasina e mi segna quel tempo. Devo riverificare.
Non lo fa sempre

**Comment by ghiboz** [comment]
si, è perchè capita che prende come posizione vicina quella finale, capita qui perchè è un *circuito* e per quello devo ancora studiare come gestirlo
