### ISSUE TITLE
Verificare scala della volta celeste di ToD 

### ISSUE THREAD

**Issue by bardo78** [gRally/dev#188]
Come da oggetto. Ho notato alla partenza, in lontananza che la cupola di ToD sembra mangiarsi un po' di environment. O almeno c'è qualche problemino perché sembrava bkinkare

**Comment by ghiboz** [comment]
il tod prende il 95% del view distance, quindi se hai come view 1000 e l'environment è più grande di 1000 te lo mangia di sicuro

**Comment by bardo78** [comment]
Io ho come View distance 6400  circa. L'environment è sicuramente più ampio. Mi sa che dobbiamo implementare la Fog... Anche come modo per mascherare il far clippping

**Comment by ghiboz** [comment]
@bardo78 con le ultime modifiche all'environment è a posto?

**Comment by bardo78** [comment]
sì.
sparito l'effetto "cielo mangia environment"
