### ISSUE TITLE
Valore force in pannello F3 non salvato

### ISSUE THREAD

**Issue by GRally-mulder** [gRally/dev#190]
Quando si modifica - e conseguentemente salva - un parametro diverso da quello standard nel trigger "forza", questo non viene memorizzato.
A dire il vero, viene memorizzato sinché non si chiude il programma, dopodiché il valore viene perso.

**Comment by ghiboz** [comment]
io ho notato un errore col bump, non con il force

**Comment by GRally-mulder** [comment]
c'è anche con il force
