### ISSUE TITLE
Replay

### ISSUE THREAD

**Issue by Gundam99** [gRally/dev#194]
1 - replay Ghiboz **OK**
2 - primo replay Gundam (tastiera fino a Bondone) **NO** 
3 - secondo replay Gundam (tastiera solo un pezzo) **OK** 
4 - terzo replay Gundam (tastiera fino a Bondone) **NO**

Altra cosa : 
nel combo del replay visualizza il nome del replay partendo dall'ultimo uderscore (primo inderscore partendo da destra)

esempio : 
- **BB_tastiera**, nel combo vedo solo **tastiera**
- **BB_test_full**, nel combo vedo solo **full**

![bb_replay](https://cloud.githubusercontent.com/assets/8404030/7759908/124f8a44-0016-11e5-8a7d-ea3aa763a903.jpg)

Posizione della barra replay nei casi **2** e **4**
![image](https://cloud.githubusercontent.com/assets/8404030/7760012/3f2f90a8-0017-11e5-9170-25841ff9c0c5.png)

**Comment by ghiboz** [comment]
dovresti provare a salvare senza _
