### ISSUE TITLE
test: motorshow spline

### ISSUE THREAD

**Issue by ghiboz** [gRally/dev#198]
@Gundam99 riesci a farmi una spline del motorshow al posto di quella attuale (3) fatta così:
 * parte dove ora;
 * fa il giro correttamente, entra nel motorshow dove ora; 
 * fa 3 giri;
 * al terzo se ne esce dalla parte dove siamo rientrati;

**Comment by ghiboz** [comment]
> questo è in previsione del tuo **Trier**

**Comment by Gundam99** [comment]
Lo trovi in gRally Tracks\Avdanced_SkidPad_FBX\splines file **spline_layout3_3_giri.xml**
