### ISSUE TITLE
Parametri del Terrain da poter modificare

### ISSUE THREAD

**Issue by bardo78** [gRally/dev#204]
Sia in ottica di scalabilità della grafica, sia in ottica di fare dei test "al volo", servirebbero questi parametri da poter inizializzare prima del gioco oppure se si può  in-game ancora meglio , però con la possibilità di salvarli...se questa cosa di salvarli è mortale, si va di carta e penna :)  

http://docs.unity3d.com/ScriptReference/Terrain-detailObjectDensity.html

http://docs.unity3d.com/ScriptReference/Terrain-detailObjectDistance.html

http://docs.unity3d.com/ScriptReference/Terrain-drawTreesAndFoliage.html  (questo dovrebbe essere un valore boolean perchè nell'editor è un "checkbox")

http://docs.unity3d.com/ScriptReference/Terrain-treeBillboardDistance.html

http://docs.unity3d.com/ScriptReference/Terrain-treeCrossFadeLength.html

http://docs.unity3d.com/ScriptReference/Terrain-treeDistance.html

http://docs.unity3d.com/ScriptReference/TerrainRenderFlags.html   (questo può esserti utile per fare la scalabilità grafica?? )

**Comment by ghiboz** [comment]
with the new things this should be old..
