### ISSUE TITLE
Specchietto retrovisore, issue multipli

### ISSUE THREAD

**Issue by GRally-mulder** [gRally/dev#211]
![immagine](https://cloud.githubusercontent.com/assets/8559142/8044580/e00d9be0-0e2d-11e5-9b06-726360334202.jpg)
1. sono in un punto della speciale ben lontano dall'inizio della speciale però...
2. ...nello specchietto vedo il punto di partenza della speciale. è come se la camera rimanesse ferma li e non seguisse la vettura
3. lo specchio è come quello "curvato" che si vede nelle vetture di tutti i giorni, per evitare gli angoli ciechi. ma nello specchio interno questo non ci dev'essere. il risultato è che si vede un'immagine spezzata.
4. la risoluzione dello specchio retrovisore è ben diversa da quella che ci si aspetterebbe è come se girasse a 512x anzichè 1680x (come è la mia risoluzione)

**Comment by ghiboz** [comment]
il problema è questo: al momento quello specchietto rappresenta solamente il riflesso come se fosse il cofano, quindi a livello di dettaglio è scarno, soprattutto se hai cambiato la risoluzione del riflesso nell'ini.

altra cosa è che essendo un riflesso così, si riflette legato alla posizione dello specchietto, è da fare con la camera, in modo da posizionarla perfetta
