### ISSUE TITLE
Sterzo

### ISSUE THREAD

**Issue by GRally-mulder** [gRally/dev#212]
Nell'ultima versione il comportamento dello sterzo è molto cambiato. bisogna resettare dei parametri?

al mio sterzare con il volante reale corrisponde un ben inferiore sterzata con il volante virtuale, tanto dal punto di vista "grafico" che "sostanziale".

**Comment by ghiboz** [comment]
mmh, no, non ho cambiato nulla di questo.. non vorrei che fosse legato a qualche impostazione del tuo volante, perchè io lo ragiono a 900° al momento
