### ISSUE TITLE
Shader macchina

### ISSUE THREAD

**Issue by ghiboz** [gRally/dev#215]
- [ ] toglierlo ingame
- [ ] nello showroom salvare la livrea completata in una tex
- [ ] ingame usare la semplice tex

**Comment by bardo78** [comment]
ma a cosa ti riferisci? :)
Non ho capito..

**Comment by ghiboz** [comment]
semplicemente ora lo shader lavora ingame, mentre voglio farlo invece solo nello showroom per cambiare al volo la livrea, ma una volta salvata, faccio salvare una sola tex che poi carico ingame
