### ISSUE TITLE
texture per illuminare le finestre delle case

### ISSUE THREAD

**Issue by ghiboz** [gRally/dev#226]
riferendomi a #225 e dopo una chiaccierata con un grande esperto @cominu che ne sa, per illuminare le finestre delle case il metodo meno dispendioso è quello del self illumination, per questo bisogna differenziare la texture della finestra da illuminare...
è possibile a questo punto fare in modo di avere un'unica texture che contenga tutte le finestre? così con un solo materiale si accendon tutte le luci!!

**Comment by Gundam99** [comment]
Giusto giusto in tempo
