### ISSUE TITLE
alcuni alberi sfarfallano con la trasparenza

### ISSUE THREAD

**Issue by ghiboz** [gRally/dev#228]
ho notato che ingame _(mi sembra che dal progetto Baitoni_Bondone non capiti)_  alcune fronde sfarfallano di bianco quando sono davanti al terreno in lontananza, lo sfarfallio sembra dato dall'alpha channel delle fronde, che passando davanti ad alcuni oggetti diventa da trasparente a bianco..

io non capisco bene come arrivare a vedere il materiale delle fronde e dello sfondo.. te che sei esperto ci dai un occhio? magari cambiando lo shader della fronda.

Magari fai un confronto con una fronda che non fa sta cosa...

grazie infinite!

**Comment by ghiboz** [comment]
è il **Terrain solo billboard set 1-4** che sfarfalla,

**Comment by bardo78** [comment]
è il deferred system con alcuni alberi che usano l'alpha (non so però perchè solo quelli).
Nel chengelog della beta attualmente rilasciata c'è qualche correzione grafica sul metodo del deferred...quindi aspetterei a fare una verifica appena esce la 5.2 che dovrebbe essere vicina.

**Comment by ghiboz** [comment]
to verify with new VS
