### ISSUE TITLE
Improvement to BB

### ISSUE THREAD

**Issue by GRally-mulder** [gRally/dev#271]
In order to make the stage even more realistic we should add:
- [ ] the red/white strips in some areas of the stage
- [ ] some road cars parked
- [ ]  one rally car parked on the side like if it's having problems (adding possibly some smoke coming out from the bonnet
- [ ]  spectators & marshall
- [ ]  some cones or other not to cut (or to cut too much) some corners

**Comment by ghiboz** [comment]
to remake..
