### ISSUE TITLE
ShowRoom

### ISSUE THREAD

**Issue by Gundam99** [gRally/dev#338]
Se chiudi gRally con lo ShowRoom aperto, va in errore

![ShowRoom_2016-10-10_20-11-58](http://www.grally.net/u/uploads/c1430171a7fb23a8325be57b6641795196165a13.png)

**Comment by ghiboz** [comment]
@punker76 I've assigned also to you, 'cause I create a showroom into a modal window and I'm able to close the main program also if the window is opened
