### ISSUE TITLE
Login menu Drive

### ISSUE THREAD

**Issue by Gundam99** [gRally/dev#340]
1 - disinstallata la versione precedente
2 - eliminata cartella gRally in documenti
3 - installata nuova versione
4 - login da drive con utenza forum (gundam), errore di windows (gRally ha snesso di funzionare bla bla bla)
5 - rientrato in gRally e login dal menu Issue (Gundam99) e tutto ok
ho dimenticato di cancellare qualche altra cartella ?
con la versione precedente ho seguito lo stesso procedimento e funzionava tutto
anche in questa versione i 2 login (drive e issue) sono diversi, giusto ?

... dimenticavo, nei controlli ho impostato la tastiera come nella versione precedente
ultima cosa :
da menu Drive ti dice di inserire l'utenza del forum, nel menu Issue ti dice sempre di inserire l'utenza del forum. Non dovrebbe venir fuori di inserire l'utenza di gitub ?

comunque mi sa che non ho cancellato qualcosa perchè, ho disinstallato la 4.3 e ho cancellato la gRally in documenti
ho reinstallato la 4.2, sono entrato nel menu Issue e mi ha tenuto l'utenza github

ultima prova :
se in drive metto user o password sbagliati, ti segnala l'errore di user o password errate
se metto gundam (utenza forum) e password corretta : gRally ha snesso di funzionare bla bla bla
mi sa che forse il problema è quando becca utenza e password corrette del forum

**Comment by ghiboz** [comment]
fixed!
