### ISSUE TITLE
new TrailBump values

### ISSUE THREAD

**Issue by bardo78** [gRally/dev#353]
Here some suggestions for the trailBump

Surface type="TARMAC" trailBump="-1"
Surface type="GRAVEL"  trailBump="-1"
Surface type="MUD" trailBump="-2"
Surface type="GRASS" trailBump="-2"
Surface type="CONCRETE" trailBump="-1"
Surface type="SNOW" trailBump="-2"
Surface type="ICE" trailBump="-1"

**Comment by ghiboz** [comment]
fixed
