### ISSUE TITLE
Sending issue and changing car livery crashes the app

### ISSUE THREAD

**Issue by KRoman47** [gRally/dev#366]
At least with upoad logs On.

**Comment by KRoman47** [comment]
[gRally_BETA_logs.zip](https://github.com/gRally/dev/files/643671/gRally_BETA_logs.zip)
logs

**Comment by ghiboz** [comment]
@KRoman47 if you send an issue without the logs enabled it works?

**Comment by ghiboz** [comment]
hi again @KRoman47 
have you got a `dump.Github.txt` file next to `gRally.exe`?
can you send me?
thanks

**Comment by KRoman47** [comment]
Sending without logs enabled works fine. I don't have any file of that name in the folder. Only those manually added logs in zip archive which I added trough web browser.
