### ISSUE TITLE
Handbrake cant be assigned as in description

### ISSUE THREAD

**Issue by KRoman47** [gRally/dev#369]
I use Fanatec pedals connected in USB, T300 also in USB, TH8RS in separate USB and T3PA pedals connected to the wheel. Handbrake cant be assigned to the T3PA pedal, I use it in Assetto Corsa since I have mounted stick at T3PA throttle pedal. Can it be allowed in future?

**Comment by ghiboz** [comment]
hi @KRoman47:
at the moment the handbrake is only `Digital`, like the steer and pedals are only `Analog`, i'm working to make available for the both controls.
