### ISSUE TITLE
Steering 

### ISSUE THREAD

**Issue by blahwalt** [gRally/dev#373]
I am having a problem getting he steering to work on my logitech g27 I can only get left or right loc not both so can only turn one way

**Comment by ghiboz** [comment]
that's strange... please try to edit manually controls.ini inside documents\gRally folder like this:
```ini
[Steering]
Goofy = false
```

let me know if works!

**Comment by KRoman47** [comment]
Just turn the first option use analog steering, it should work then.
![image](https://cloud.githubusercontent.com/assets/24479006/21390782/dbcf85aa-c788-11e6-82d9-3162cffd1b58.png)

**Comment by blahwalt** [comment]
Sorry I haven't got back to you about this I've been flat out at work I changed the ini file and that work haven't had a lot of time to try it out but should get some time this weekend.
Thanks for thr help and keep up the good work

Get Outlook for Android<https://aka.ms/ghei36>



On Tue, Jan 3, 2017 at 11:17 PM +1300, "Paolo Ghibaudo" <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #373<https://github.com/gRally/dev/issues/373>.
