### ISSUE TITLE
Invert handbrake axis doesnt work

### ISSUE THREAD

**Issue by KRoman47** [gRally/dev#374]
As title says, when I enable invert handbrake axis it doesnt work and even messes up the brake controls.

**Comment by ghiboz** [comment]
can you send me the controls.ini file inside documents/gRally folder?
and also a shot of your config page
thanks

**Comment by KRoman47** [comment]
![image](https://cloud.githubusercontent.com/assets/24479006/21390373/e2d4c3b2-c786-11e6-897f-73b0473438c0.png)
[controls.zip](https://github.com/gRally/dev/files/666393/controls.zip)
