### ISSUE TITLE
Godrays causing graphical issues at night

### ISSUE THREAD

**Issue by KRoman47** [gRally/dev#375]
As title says, when godrays are turned on at night the moon has very unnatural glow, the effect probably should be lower.

**Comment by KRoman47** [comment]
![image](https://cloud.githubusercontent.com/assets/24479006/21390596/f98758c6-c787-11e6-8835-9015689d5da4.png)

**Comment by ghiboz** [comment]
lol! ghosts into the stage!!
back serious.. I think that depends by the moonlight, the godrays may be only for the sun 🥇

**Comment by gRally** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [togliere godrays dalla notte](https://trello.com/c/scKsDh5z/33-togliere-godrays-dalla-notte)
