### ISSUE TITLE
FFB while driving in reverse gear

### ISSUE THREAD

**Issue by dgantar** [gRally/dev#382]
When driving in reverse gear, even at low speed, steering wheel FFB(T300 wheel) becomes very fast. At first it cought me off-guard that I almost snapped my wrist.
In my opinion these forces are bit exaggerated/overstaturated, while normal forward driving is okay.

Example(Skid pad on tarmac): standing still, steering 90° to the left or right and then drive off, FFB bites/snaps very fast to the tire respone.
At 10-20° off center seems to be okey (wheel doesnt shake much).

**Comment by ghiboz** [comment]
hi @dgantar! I've optimized this thing... can you test please?
