### ISSUE TITLE
Car can be control in replay

### ISSUE THREAD

**Issue by smallfathim** [gRally/dev#383]
The car keep flipping and floating in the air in replay, and I can steer and gas IN THE REPLAY.
Then the game crashed with a error message.

**Comment by ghiboz** [comment]
hi! this happens each time? happens with all the replays? can you send me the replay?

**Comment by smallfathim** [comment]
I experienced that once, not sure is it common in every replays.....and i don't have the replay now, it's been a while from now, around 4-5 build before.

Jason

**Comment by ghiboz** [comment]
ok Jason, I close, if the problem persists, please recreate a new issue!
thanks 🐰

**Comment by smallfathim** [comment]
Got it.

Jason
