### ISSUE TITLE
Godrays on turn off carlights

### ISSUE THREAD

**Issue by bardo78** [gRally/dev#387]
From the 20PM to 4 AM, if you set Godrays on, the carlights will be turned off.

**Comment by FranK45** [comment]
I have the same issue. Good to know it's from the GodRays.

**Comment by ghiboz** [comment]
can you retry now? thanks

**Comment by FranK45** [comment]
Sorry, I was out for a while.

I tested it in Akagi Downill. The lights works now before 4am with godrays, but all vegetation disappears.

**Comment by ghiboz** [comment]
np Frank! can you make some shot please?

**Comment by FranK45** [comment]
![untitled - w godrays](https://user-images.githubusercontent.com/2703601/28884212-f23dd426-777e-11e7-9a31-9c89c548676f.png)
![untitled - wo godrays](https://user-images.githubusercontent.com/2703601/28884213-f2412522-777e-11e7-9606-a908ba8e0ff1.png)

**Comment by FranK45** [comment]
I also just tried in Power Stage. Trees are ok. But i realized that the GRALLY banner also disappears as well as the white paint lines on the tarmac.
![image](https://user-images.githubusercontent.com/2703601/28884344-7aa54362-777f-11e7-95a7-7e2f45dbffa4.png)
![untitled - wo godrays](https://user-images.githubusercontent.com/2703601/28884353-80fbcac4-777f-11e7-8eea-659a35545c09.png)
