### ISSUE TITLE
Game crash during power stage

### ISSUE THREAD

**Issue by FranK45** [gRally/dev#389]
Game crashed during power stage, first lap and first play with 4.11

**Comment by FranK45** [comment]
Game crashed on loading after retry. Restarting the game and worked ok afterward.

**Comment by ghiboz** [comment]
hi @FranK45 
with the new release crash or not?

**Comment by FranK45** [comment]
No crashes at all with the latest release!

**Comment by ghiboz** [comment]
glad to read this!
