### ISSUE TITLE
Replay is not working

### ISSUE THREAD

**Issue by FranK45** [gRally/dev#390]
Replay is not working, the car sets and does backflips. Also the mouse is hidden when moved.
### [log](http://www.grally.net/u/uploads/134bb4623a3bf76030849722288c6274dbf40789.zip)

[Akagi-0.2_1_TestAK 4.11.zip](https://github.com/gRally/dev/files/815610/Akagi-0.2_1_TestAK.4.11.zip)

**Comment by ghiboz** [comment]
this should be ok in the new version, if not please create a new issue.. thanks!
