### ISSUE TITLE
very low fps if i change pacenotes from ITA to ENG co- driver.

### ISSUE THREAD

**Issue by BANDIT1977** [gRally/dev#393]
with ALLESADRINI  pacenotes 200 fps when go to GRIST 38-44 FPS.steam version.check more than 30 times same problem.thanks in advance

**Comment by ghiboz** [comment]
here it works right....
can you send me the logs?

**Comment by BANDIT1977** [comment]
I don't receive error or crash..just the fps on screen is low....compare to Italian pace notes.italian 200fps English maximum 40.thats my issue.I hear normal both but I can't play with English pacenotes .thanks

**Comment by BANDIT1977** [comment]
my log.
[log.zip](https://github.com/gRally/dev/files/892976/log.zip)
[log.zip](https://github.com/gRally/dev/files/892978/log.zip)

**Comment by ghiboz** [comment]
I tried here and no difference... does anybody can test?

**Comment by bardo78** [comment]
Alessandrini -> 270FPS on Advanced Skidpad
Grist -> 70 FPS on Advanced Skidpad

**Comment by ghiboz** [comment]
fixed in v0.5.1.5
