### ISSUE TITLE
realign the position of the start red flag sing in Los Marteles downhill.

### ISSUE THREAD

**Issue by BANDIT1977** [gRally/dev#394]
![20170404150819_1](https://cloud.githubusercontent.com/assets/26834514/24656045/755f77cc-1949-11e7-8353-27a056943737.jpg)
![20170404150805_1](https://cloud.githubusercontent.com/assets/26834514/24656048/793f48b8-1949-11e7-9695-a50a4f51dc9b.jpg)

**Comment by ghiboz** [comment]
fixed in v0.5.1.5
