### ISSUE TITLE
Repeatitive Crashes while loading game

### ISSUE THREAD

**Issue by FranK45** [gRally/dev#395]
Hi,

I started an played the game fine, disabled bloom and changed car setup and played fine. After then I was not able to start the game again, getting an error while loading the race. I restarted the game and still got the same crash.

Best regards,
[log.zip](https://github.com/gRally/dev/files/894661/log.zip)

**Comment by GBratsos** [comment]
Try a reinstallation of the game, along with a CCLeaner clean up. Don't forget to delete the folder from the Documents.

**Comment by ghiboz** [comment]
did you use the english pacenotes? #393

**Comment by FranK45** [comment]
Well, finally back home.

The new update (0.5.1.5) have fixed the issue.

And yes I was using the english pacenotes on both versions.

**Comment by ghiboz** [comment]
good!!! at the moment I close it, if the problem persists please open a new issue ;)
