### ISSUE TITLE
Cluster with ligts on - only white RPM needle

### ISSUE THREAD

**Issue by FranK45** [gRally/dev#401]
When I turn on the headlights. The only change in the cluster is the RPM needle that goes fully white.

**Comment by GBratsos** [comment]
This happened to me too. In general there is much white on everything including the sky on the steam version.

**Comment by FranK45** [comment]
Here is a picture of the issue

![rpm-needle-white-headlamp](https://cloud.githubusercontent.com/assets/2703601/25204936/df919590-252d-11e7-828d-8e234b64eb70.png)
