### ISSUE TITLE
Game crashes after the last 3 updates.

### ISSUE THREAD

**Issue by GBratsos** [gRally/dev#402]
Opened the main menu, did some tweaking on graphics, started the Power Stage and when the stage started loading the game crashed giving my this log.

Didn't delete any Documents folder etc.

[output_log.txt](https://github.com/gRally/dev/files/935875/output_log.txt)

**Comment by ghiboz** [comment]
this hapened once or now you aren't able to play the power stage? please try also with akagi or los marteles

thanks @GBratsos

**Comment by GBratsos** [comment]
This happens when i'm trying to load any stage and my wheel is not connected.

If i connect my wheel everything works fine!

**Comment by ghiboz** [comment]
good to hear this! see ya in the stages! 👍
