### ISSUE TITLE
Discuss about the 'finish' or 'retire' action

### ISSUE THREAD

**Issue by ghiboz** [gRally/dev#404]
At the moment, when you retire or finish the rally, in the live section appears the roadbook with the standings: it's right or not?
maybe adding a 'Results' section and removing this will be good!

**Comment by bardo78** [comment]
Why do you think it's not good to see automatically the standings? 

At the moment I think it's fine to check everything is fine in terms of save times, change stage, apply setups, and all the racing logic behind a complete rally. 

Later, when we'll the whole picture I think it will be easier to organize all these question. 

At the moment I don't have a precise idea about your question.
