### ISSUE TITLE
Graphic glitch at resolution 2560x1440

### ISSUE THREAD

**Issue by GBratsos** [gRally/dev#427]
Hello all,

I recently bought a new monitor with 2560x1440 resolution @144hz. I just opened gRally and when i roll-over to the menu with my mouse they became black. When i did it again they came back to normal. (Screenshot 1)

Also, on steam I've the FPS indicator and when i clicked anywhere on the menu the Screenshot 2 happened.

![fps_indicator](https://user-images.githubusercontent.com/3661790/33333760-6211bb0c-d470-11e7-96d1-2e1117bffd9d.png)
![graphic_glitch](https://user-images.githubusercontent.com/3661790/33333761-6232a434-d470-11e7-9342-192a82d82677.png)

I think that's something with the particles or something because when I changed my resolution to 1920x1080 everything works smoothly.

Also i cannot create a GitHub issue from inside the game. It keeps loading when I tried to upload an image or my log.zip file.
[log.zip](https://github.com/gRally/dev/files/1510933/log.zip)

**Comment by ghiboz** [comment]
@GBratsos @Gundam99 please can you try with the new release to add in `documents\gRally\gRally.ini` the parameter

```ini
[misc]
DisableHardwareAcceleration = true
```

and start the game?

thanks
