### ISSUE TITLE
Showroom issues

### ISSUE THREAD

**Issue by gRally-Issues** [gRally/dev#430]
# User: marcatore
---
2 little things

1- Where there are the RGB sliders, I see just the "R" value and not the "G" and "B".

2- I think it will be useful to save the favourite colors so when you close the showroom and you open it again, you'll find them again. It will be useful, for example, to port the same colors to a car from another one.

**Comment by ghiboz** [comment]
@bardo78 
the `RGB` sliders are all 3...
![](https://i.imgur.com/QDcexrb.png)
about the `2`, yes, I'll use the fav colors below able to save and reload

**Comment by bardo78** [comment]
About the first point, I was speaking about the color values. If you look, just the R channel value is visible. The other ones not, just a "-"
