### ISSUE TITLE
Audio

### ISSUE THREAD

**Issue by gRally-Issues** [gRally/dev#434]
# User: Save
---
After abig update of windows now i'm not able to ear audio in game. No problem with other games or app. I've uninstalled and reinstalled all, but no audio at all. Any solution?

**Comment by ghiboz** [comment]
hi @Save1978 
this should be something of windows configuration...
gRally uses the default windows playback device
have you tried looking the mixer when you play?
![](https://i.imgur.com/t2te85N.png)

**Comment by Save1978** [comment]
Yes. I've looked up. I changed output device and reinstalled software more
time, but no sound at all. Is it possible is there a key register to be
removed or changed?

Il 31 dic 2017 11:45, "Paolo Ghibaudo" <notifications@github.com> ha
scritto:

**Comment by ghiboz** [comment]
@Save1978 
http://drive.google.com/uc?export=download&id=0B0vVb1oBPqJtNXFqSlNiRUo0aEE
here is a playable demo of this: https://www.assetstore.unity3d.com/en/#!/content/87494
is made with unity and has a audio...
could you try to test this?

**Comment by Save1978** [comment]
Street racing works perfectly, but  grally no...frustrating

2017-12-31 12:12 GMT+01:00 Paolo Ghibaudo <notifications@github.com>:

**Comment by Save1978** [comment]
[SOLVED] Disabled every single audio output except the only one i use,
resart working

Il 01 gen 2018 18:27, "Valeriano Bellinzoni" <vbellinzoni@gmail.com> ha
scritto:
