### ISSUE TITLE
Direct Drive Wheel oscelation and wrong center point issue

### ISSUE THREAD

**Issue by gRally-Issues** [gRally/dev#435]
# User: DjFIL007
---
Appears to calibrate in config with no issues, though deadzone large.  But when loading stage as loads car (I'd guess) the FFB goes in to immediate oscelation.  I have to interject to stop this motion (by hand or stop switch).  When game loads and I've stopped rotation, the center point of the wheel is no longer at true north.  Tried loading a few times, it's always stopped at about "8 o'clock".

**Comment by DjFIL007** [comment]
My comment.  Subscribed to follow and provide anything else I can.

**Comment by ghiboz** [comment]
hi @DjFIL007 
when you enter in the cockpit, the wheel go to centered..
I look your log, and this should be the cause:
```ini
[Steering]
DeviceName = MMos ForceFeedback 2014
...
Values = -11, 32767
```
the `Values` field should be like this:
```ini
[Steering]
DeviceName = MMos ForceFeedback 2014
...
Values = -32768, 32767
```
please try changin' this in `documents\gRally\controls.ini` before to launch gRally and let me know!
