### ISSUE TITLE
VR problem

### ISSUE THREAD

**Issue by gRally-Issues** [gRally/dev#440]
# User: Save
---
On the left eye ther  is the right view, on the rught you can see only the body of the car. View is not inside the car in fron of the cockpit. Something about allignment seems wrong...

**Comment by ghiboz** [comment]
have you tried pressing together left and right view buttons?
it center the view

**Comment by Save1978** [comment]
I"ll try but i don't think it's an alignment problem. I think it's
something wrong in rendering view

Il 14 gen 2018 12:05, "Paolo Ghibaudo" <notifications@github.com> ha
scritto:

**Comment by ghiboz** [comment]
can you reach to send a shot of the 'monitor' ?

**Comment by ghiboz** [comment]
have you installed `SteamVR` ?

**Comment by Save1978** [comment]
Yes and updated. I use usually with iRacing and rF2 without any problem

Il 18 gen 2018 09:55, "Paolo Ghibaudo" <notifications@github.com> ha
scritto:

**Comment by finagle69** [comment]
I had this same issue last night.  I use a Rift, and chose Oculus in the launcher settings.  It does the same with OpenVR as well.

If Oculus is chosen, shouldn't it not open SteamVR but use Oculus runtime directly?

**Comment by ghiboz** [comment]
have you got a shot or video to identify the issue?
with the rift (dk2) seems ok...

remember that the 2 buttons used to look left/look right with the monitor, used together will recenter the VR

@finagle69 should be right, but I'm looking to use SteamVR, that automatically work with Rift or Steam..

**Comment by finagle69** [comment]
This issue is fixed for me with your latest update :)
