### ISSUE TITLE
Suspension physics glitch?

### ISSUE THREAD

**Issue by gRally-Issues** [gRally/dev#448]
# User: DjFIL007
---
Got caught up early in the stage on a bollard.  Broke the wheel right off my car, but it appears when this happened some invisable suspension geometry (a guess) got tangled with the bollard and sent me along for a wild ride.  Check out the replay, hopefully helps you to locate the issue.

[Los_Marteles-0_1_woah](https://www.grally.net/u/uploads/5a5c48c1aa3bba99a30ba536464ce29da464c652.rpl)

**Comment by DjFIL007** [comment]
Posting to follow replies about this interesting glitch.
