### ISSUE TITLE
Los Marteles wrong Flag

### ISSUE THREAD

**Issue by GBratsos** [gRally/dev#459]
Wrong country flag for Los Marteles stage

![losmarteles](https://user-images.githubusercontent.com/3661790/37878177-56a79e86-306d-11e8-958e-43ee871261da.png)

**Comment by ghiboz** [comment]
you need the latest stage version: 
https://github.com/gRally/dev/wiki/Manual-Mods 
http://www.ghiboz.com/gRallyMods/Los_Marteles/Los_Marteles-0.4.0.grMod
