### ISSUE TITLE
Today's update has broken Seprate Rendering under Triple Screen settings.

### ISSUE THREAD

**Issue by gRally-Issues** [gRally/dev#462]
# User: DjFIL007
---
Today's update has broken Seprate Rendering under Triple Screen settings.

Without works fine.  tested multiple stages.

**Comment by DjFIL007** [comment]
Sorry, to be clear the left and right displays aren't working.  centre display is working normally.  Black screen on left/right in gameplay; in menus and pause overlay, they take up full width of 3 displays.

**Comment by ghiboz** [comment]
Hi found the issue, should be fixed in the next release.. meanwhile to make it works, you should enable the mirrors :+1:
