### ISSUE TITLE
Menu is broken, can't change controls

### ISSUE THREAD

**Issue by gRally-Issues** [gRally/dev#495]
# User: Heikki360
---

#### What happened?

The main menu is completely broken, shows info of other Windows programs and i can't change anything in the controls section. Tried with and without wheel (Fanatec CSW v2), same goes for the XBOX One controller. Looks like the problem is the menu, not the controls. I can't assign the controls (buttons or axes).

**Comment by ghiboz** [comment]
please try to add this line in `documents\gRally\gRally.ini`
```ini
[misc]
DisableHardwareAcceleration = true
```
