### ISSUE TITLE
Fanatec CSW v2.5 not working

### ISSUE THREAD

**Issue by gRally-Issues** [gRally/dev#497]
# User: Tesnaukki
---

#### What happened?
I was trying to map controls to my Fanatec CSW v2.5 wheelbase and CSP v3 pedals but it didn't detect any controls
#### Steps to reproduce:
Acquire CSW 2.5 wheelbase, P1 elite rim, and Clubsport v3 pedals and try to map controls.
#### Considerations...
Please?

**Comment by gRally** [comment]
should fixed in the new versions
