### ISSUE TITLE
Game crash while loading

### ISSUE THREAD

**Issue by gRally-Issues** [gRally/dev#500]
# User: Tesnaukki
---

#### What happened?
Game crashed while trying to enter a stage
#### Steps to reproduce:
Drive -> Choose gArena and G1 and while on the loading screen the game crashes
#### Considerations...
In the future please be more specific what you need to know in these bug reports
[crash](https://www.grally.net/u/uploads/5dd6566cebb3dcf674d03dba24c69042e77f98d2.dmp)

**Comment by ghiboz** [comment]
does it happens always or sometime?

about these reports: you're clear: every thing I need is ok!

**Comment by gRally** [comment]
your controls are set correctly?
