### ISSUE TITLE
Can't start

### ISSUE THREAD

**Issue by gRally-Issues** [gRally/dev#501]
# User: Mertcan Solak
---

#### What happened?
My controls are OK but I can't start.Car is not going.I see "30" on the top right
#### Considerations...

![20180521194854_1](https://www.grally.net/u/uploads/205f7ee93f675085c0b15a80eaf7bcb126d18e52.jpg)

**Comment by ghiboz** [comment]
you need to press and release the handbrake..
in the latest version a message indicate you how to do
