### ISSUE TITLE
Fanatec controls wont work

### ISSUE THREAD

**Issue by gRally-Issues** [gRally/dev#503]
# User: Tesnaukki
---

#### What happened?
My controls arent detected in the control mapping window, I click the button on the top left of the window but nothing happens when I move the controls.
#### Steps to reproduce:
Fanatec CSW2.5 wheelbase, Clubsport Pedals v3, Fanatec Shifter and P1 elite rim, all connected to the wheelbase.
#### Considerations...
See the picture below
![fanatecgrally](https://www.grally.net/u/uploads/327285063eecaa5c9107da358b54f8c5e9689b55.PNG)

**Comment by PibeBianchi** [comment]
I have the csl elite with club sport v3 inverted, fanatec shifter 1.5, handbrake, p1 elite rim and all of theme works

**Comment by ghiboz** [comment]
have you looked this guide? 
https://youtu.be/gBr0B5V9r3Y
when you select with the radio rounded button which control 'calibrate', please move it 'fast', 'cause to be detected as 'new calibration axis' I need to have a input change in a time step... and to avoid some imputs that have a little noise, I put a threshold

**Comment by gRally** [comment]
with the latest version should work
