### ISSUE TITLE
Unable to drive

### ISSUE THREAD

**Issue by gRally-Issues** [gRally/dev#504]
# User: CaptainCoffee ?
---

#### What happened?
Tried to drive, but nothing happens

#### Steps to reproduce:
Open the game
Setup wheel (G920) and pedals
Drive with either car on the default track
Change gears work, throttle works, but brakes and clutch are always fully pressed

#### Considerations...
Not sure if there are other screens with logs to display what might be causing the false input...

**Comment by mertcansolak** [comment]
I had same problem.You should set handbrake button then when you enter the game,first of all,click handbrake button,after this you can drive
