### ISSUE TITLE
H-shifter not working

### ISSUE THREAD

**Issue by gRally-Issues** [gRally/dev#505]
# User: Fordy
---

#### What happened?
When I turn on h-shifter and want to drive controls just don't respond in a car and it looks like throttle is pushed halfway even when I'm not touching pedals. In menu, on other hand, all binding is still set and responding.
#### Steps to reproduce:
Allow h-shifter and go driving

**Comment by ghiboz** [comment]
when you enable the h-shifter and try to shift, you see the gears icon red?

**Comment by f0rdy** [comment]
Yes, in menu everything is working, but in car controls not respond
