### ISSUE TITLE
Can't assign controls on Fanatec CSL Elite and pedals

### ISSUE THREAD

**Issue by gRally-Issues** [gRally/dev#506]
# User: jbaessens
---

#### What happened?
Can't assign controls on Fanatec CSL Elite and pedals, no values displayed. Just the 3 usb devices are displayed.

#### Considerations...
Perhaps it's because Fanatec is detected as two devices.. ?
![Sans titre](https://www.grally.net/u/uploads/4423804afc73a8dd0a3b839600050c56f29987e5.png)

**Comment by ghiboz** [comment]
please check this #503
