### ISSUE TITLE
Error with sync

### ISSUE THREAD

**Issue by gRally-Issues** [gRally/dev#507]
# User: ErAbutardoDerranker | WeeD
---

#### What happened?
Hi, i can´t sync steam with the forum
#### Steps to reproduce:
trying to sync on forum , it says
" Undefined offset: 1

XenForo_Application::handlePhpError() in Steam/ControllerPublic/Register.php at line 655
Steam_ControllerPublic_Register->_validate() in Steam/ControllerPublic/Register.php at line 48
Steam_ControllerPublic_Register->actionSteam() in XenForo/FrontController.php at line 347
XenForo_FrontController->dispatch() in XenForo/FrontController.php at line 134
XenForo_FrontController->run() in /var/www/forumgrallydir/index.php at line 13"

#### Considerations...
I hope u get the sim running, big thanks to u for developing this game to us .

**Comment by ghiboz** [comment]
fixed now
