### ISSUE TITLE
Can't setup controls

### ISSUE THREAD

**Issue by gRally-Issues** [gRally/dev#510]
# User: ??
---

#### What happened?
Controls setup is unresponsive, no matter what I do or click it doesn't let me change the controls (but it shows I'm selecting something, I can move the sliders etc.). It detects my peripherals, but can't assign them, not even keyboard buttons can be assigned.

**Comment by ghiboz** [comment]
please watch this video:
https://youtu.be/gBr0B5V9r3Y

**Comment by pawnisher** [comment]
Yup, that's exactly what doesn't work. I can select the box but after that nothing happens, it doesn't register and change my inputs.

**Comment by gRally** [comment]
please try the new release
