### ISSUE TITLE
Problem with steering w/ Open Sim Wheel (SimuCube)

### ISSUE THREAD

**Issue by gRally-Issues** [gRally/dev#511]
# User: WilliamSRP
---
Wheel does not properly match the settings, and Force Feedback tries to kill me

Enter the Sim, and the steering automatically breaks itself. 

#### Considerations...

Fix the steering to match the settings.

**Comment by ghiboz** [comment]
you made a wrong config:
please in the `controls.ini` change the values like this:
```ini
DeviceName = SimuCUBE
Device = 0
Type = 0
Item = 0
Fk = 0
Inv = false
Linear = 1.0030769109726
Values = -32768, 32767
```
