### ISSUE TITLE
Crash with Immersion-based steering wheel ECCI 7000

### ISSUE THREAD

**Issue by gRally-Issues** [gRally/dev#516]
# User: fourier
---

#### What happened?
The game crashes on attempt to start 
#### Steps to reproduce:
Start a game
Select Drive
Click on Drive! button
#### Considerations...
Probably because of my Immersion-based Steering wheel ECCI 7000

[Crash_2018-05-21_224754](https://www.grally.net/u/uploads/8b36f1e7858932448f9d2cd0cc6e602f543129f8.zip)

**Comment by ghiboz** [comment]
hi!
can you send me the `controls.ini` and `gSim.log` inside `documents\gRally'?

**Comment by fourier** [comment]
Here it is
[gRally.zip](https://github.com/gRally/dev/files/2042953/gRally.zip)

**Comment by gRally** [comment]
please try the new release
