### ISSUE TITLE
Physics glitches out when pressing "compass" button

### ISSUE THREAD

**Issue by gRally-Issues** [gRally/dev#517]
# User: cheba
---

#### Considerations... What is the "compass" button supposed to do anyway? Reset the car to the stage? One time when I tried it, it actually did drop the car back on the stage. It wasn't a smooth drop, but at least the physics didn't go crazy.

The button needs some text to explain what it's supposed to do.

**Comment by ghiboz** [comment]
at the moment the button is removed, waitin to fix it (1.0.1.1)
