### ISSUE TITLE
Graphic problems

### ISSUE THREAD

**Issue by gRally-Issues** [gRally/dev#520]
# User: PibeBianchi
---
Ciao ragazzi, innanzitutto grazie per dare un'alternativa a rbr ma ora passiamo ai problemi che ho riscontrato

#### What happened?
La grafica sembra non funzionare

#### Steps to reproduce:
appena ho avviato il gioco ho cercato di mettere le impostazioni grafiche al massimo ma a quanto pare qualcosa non ha funzionato

#### Considerations...

![gRally_2018-05-21-23-23-34](https://www.grally.net/u/uploads/81d6e28a0efd15490593bbf4684f7ff051ca151e.png)

**Comment by ghiboz** [comment]
fixed with 1.0.1.1
