### ISSUE TITLE
Fanatec gear Working

### ISSUE THREAD

**Issue by gRally-Issues** [gRally/dev#521]
# User: DaNiFLY82
---

#### What happened?
I have a Fanatec v2.5 wheel base, BMW GT2 rim, v3 Pedales and SQ1.5 shifter + USB handbrake. I can´t bind anything, Control Setting I see [0] Fanatec [1] USB Gamepad (handbrake) [2] Fanatec, so it is reading it but nothing works.

**Comment by ghiboz** [comment]
duplicate of #524
