### ISSUE TITLE
dont start to drive

### ISSUE THREAD

**Issue by gRally-Issues** [gRally/dev#526]
# User: Mau Max
---

#### What happened?
the game wont start, when press to drive.

#### Steps to reproduce:
Already tried lowering all kind of settings and nothing happened

#### Considerations...
what can I do?

[dump.UnhandledException](https://www.grally.net/u/uploads/b65c812e3469cbe6f29fe5980a37179544c70979.txt)

**Comment by ghiboz** [comment]
seems that you doesn't have `MOIS.dll`
 in your install folder:
![](https://i.imgur.com/hln51FU.png)

[MOIS.zip](https://github.com/gRally/dev/files/2025896/MOIS.zip)
here is the file: please check if your antivirus locked this file
