### ISSUE TITLE
Cant configure g29 brake

### ISSUE THREAD

**Issue by gRally-Issues** [gRally/dev#529]
# User: Hidant
---

#### What happened?
Was trying to do first time config to use with the wheel, now when pressing it in the controller options, It doesnt show me the force graph, just the axis numbers, I will try to see if the issue its on my end either way.

**Comment by ghiboz** [comment]
as fast fix, please edit your `documents\gRally\controls.ini` like this:
```ini
[Brake]
DeviceName = Logitech G29 Driving Force Racing Wheel USB
Device = 0
Type = 0
Item = 1
Fk = 6.5
Inv = true
Linear = 1
Values = 32767, -32768
Digital = false
Goofy = false
```
