### ISSUE TITLE
Cant change Controls (Simucube,HE Pedals)

### ISSUE THREAD

**Issue by gRally-Issues** [gRally/dev#539]
# User: AHR masta2k9
---

#### Considerations... maybe a Manual could help?

[log](https://www.grally.net/u/uploads/c1b5f39e82e0c915971a89763df41e30c9f6bd65.zip)

**Comment by DjFIL007** [comment]
Can you try and disconnect few items (say down to just wheel and\or pedals) and map just them?  Just asking as a fellow OSW Simucube user who has no issues in gRally (while in Closed Beta using MMos, and before end of Closed Beta and now with Early Access release using SimuCUBE firmware 0.9.9)... my other inputs are SLI-Pro (buttons/display), TH8A (used as analog handbrake) and Fanatec CSR Elite pedals (all items as separate USB inputs).

**Comment by ghiboz** [comment]
please read also #503
