### ISSUE TITLE
Steering wheel rotation angle

### ISSUE THREAD

**Issue by gRally-Issues** [gRally/dev#542]
# User: osiek
---

#### What happened?
I have Thrustmaster T100 (aka F430) FFb. It has only 240 rotation. So I set 240 angle in steering wheel config. But then in game wheels were only turning like 1/3 of maximum angle.

#### Considerations...
I set 900 angle in config. Then, everything works just fine.

**Comment by ghiboz** [comment]
and in menu the wheel rotates correctly?

**Comment by OsiekRC** [comment]
Yes. It works fine in menu.
