### ISSUE TITLE
Thrustmaster F430 Force Feedback not recognized at all

### ISSUE THREAD

**Issue by gRally-Issues** [gRally/dev#544]
# User: nost1972
---

#### Considerations...

in the Config screen, selecting analog steer, nothing happens: the keybord is still listed everywhere. Also selecting the radio buttons and doing whatever, the wheel does not give any sign of life. This wheel is perfectly working in other games (RBR, Dirt Rally to name two). Anything I should do?

**Comment by nost1972** [comment]
there is no list at the center of the screen. In each option (steering, brake, etc) there is "keybord" written in the grey line. I tried connecting only the wheel and no controllers, or connecting a controller and no wheel. Still only keyboard available. Wheel and controllers are correctly recognized by other games. Thanks for any suggestion

**Comment by ghiboz** [comment]
please try with the new version
