### ISSUE TITLE
grafik problem

### ISSUE THREAD

**Issue by gRally-Issues** [gRally/dev#545]
# User: Hampus Wallin
---

#### Considerations...
 fist pix is wrong

![Capture001](https://www.grally.net/u/uploads/5f55c9e7711ade1e6bf53c41767129ba2afe606b.png)

![grally bild](https://www.grally.net/u/uploads/6c4ff94b92bbf2d7efa59b720493318540a74f10.jpg)

**Comment by ghiboz** [comment]
please set max texture level to 8 and if you have VR connected and don't want to use, power off it!
