### ISSUE TITLE
Bug report "Car Will Not Move" can be closed

### ISSUE THREAD

**Issue by gRally-Issues** [gRally/dev#548]
# User: MagicDoorHinge
---

I found out the cause of my issue where the car would not move and I feel foolish... I had the handbrake mapped to my joystick and when the joystick was in the center position (not at either end of its axis) it was locking the rear wheels entirely.

Follow-up question: do you know of a way to change it in-game so that the center position of my joystick is all the way negative, and the edge of the joystick's axis is all the way positive? Otherwise I can use a program like Joy2key to change it myself.

**Comment by ghiboz** [comment]
hi! thanks for your reply:
please try to explain better: what control are you refering? steer or one of the pedals?
