### ISSUE TITLE
the elite fanatec csl base does not work

### ISSUE THREAD

**Issue by gRally-Issues** [gRally/dev#551]
# User: mariofusti
---

#### Considerations...
the elite fanatec csl base does not work

**Comment by ss0n** [comment]
I would like to say it works for me, maybe something wrong in your conf

**Comment by ghiboz** [comment]
please try to edit `documents\gRally\controls.ini` and edit the wrong values:
```ini
[Steering]
DeviceName = FANATEC CSL Elite Wheel Base
Device = 1
Type = 0
Item = 2
Fk = 0
Inv = false
Linear = 0.996153831481934
Values = -32768, 32767
Digital = false
WheelAngle = 999
Goofy = false
```
