### ISSUE TITLE
wheel is not aligned

### ISSUE THREAD

**Issue by gRally-Issues** [gRally/dev#560]
# User: Frosted
---
i copied someone's wheel settings and now the only way for my car to go straight is of im at full lock to the left. If there is anything that could help me fix this it would be appreciated thanks

**Comment by ghiboz** [comment]
hi!
please open `documents\gRally\controls.ini` and edit the `values` line under `[steering]` like this:
```ini
[Steering]
DeviceName = Logitech G29 Driving Force Racing Wheel USB
Device = 0
Type = 0
Item = 1
Fk = 0
Inv = false
Linear = 0.993076920509338
Values = -32768, 32767
```
