### ISSUE TITLE
xbox one controller - brake and throttle on combined axis

### ISSUE THREAD

**Issue by gRally-Issues** [gRally/dev#567]
# User: Siegfried Grimme
---

#### What happened?
In the controller menu both the throttle and brake analog buttons are mapped to a combined axis.
Whenever you press the throttle, pressing the brake will reduce the throttle and vice versa.

#### Steps to reproduce:
Can be reproduced directly in control config menu.

#### Considerations...

Please offer a combined axis option to separate the brake and throttle function on controllers like the xbox one controller.

**Comment by ghiboz** [comment]
the issue is related to the xbox controller that works in combined axis using directinput..
