### ISSUE TITLE
My Rally Event Today

### ISSUE THREAD

**Issue by DjFIL007** [gRally/dev#584]
Decided to make as one post, was quite the adventure... with not the best ending.

First stage, no issues at all... had the run of my life and was 2nd for the stage (at that time).

Second stage, while I wasn't as fast, no issues during the run itself, but as I cross the finish line I see that the menu has crashed.  simulator crashes soon after

Reboot, back to menu for stage 3... game is freezing as it tries to load my profile... stuck at...

![grally_slowlogin](https://user-images.githubusercontent.com/14816160/40572706-c6509aa6-6067-11e8-9fbe-4011e3e91e1f.png)

takes upwards of 15-20 seconds... if i click anywhere windows thinks it's not responding and wants to close.  once i learn to be patient, i am able to try to continue my rally.  But as i try to start stage three i'm greeted with...

![grally-error](https://user-images.githubusercontent.com/14816160/40572703-a14ec912-6067-11e8-971e-312dd4e89880.png)

after pressing ok (or x... was able to repeat error) it would then go to load a stage, but it was loading gArena (not Reinsberg 1 as scheduled). no point in running the wrong stage.  had to exit and quit the event never getting to run stage 3.  I'm unsure if others were having similar issue tonight, as at the time I had withdrawn, it appeared 1/2 the rally did too before getting to run the 3rd stage.

More logs for your pleasure...

[DxDiag.txt](https://github.com/gRally/dev/files/2041305/DxDiag.txt)

[grallycrash2.txt](https://github.com/gRally/dev/files/2041306/grallycrash2.txt)

[grallycrash.txt](https://github.com/gRally/dev/files/2041307/grallycrash.txt)

[dump.UnhandledException.txt](https://github.com/gRally/dev/files/2041308/dump.UnhandledException.txt)

[gSim.log](https://github.com/gRally/dev/files/2041309/gSim.log)

Hope this helps, thanks for the good work on bug crushing guys.

**Comment by ghiboz** [comment]
fided on v1.0.7.8
