### ISSUE TITLE
Generic USB Joystick

### ISSUE THREAD

**Issue by gRally-Issues** [gRally/dev#585]
# User: SyFy
---

#### What happened?
I use custom made USB sequential shifter and i see it listed as [0] in game Controls menu but i can't map it as it seems inactive. The other controls [1], [2], [3] are ok.
#### Considerations...

[log](https://www.grally.net/u/uploads/9a2fd06e3b430a745f17ba8fdda6828697299baf.zip)

![Clipboard01](https://www.grally.net/u/uploads/e53fe86184422988af30db036fd40f3d55b40ad9.jpg)

### [log](https://www.grally.net/u/uploads/0ebf99bf094a9b423b0866bd88010c3023465ff8.zip)

`v1.0.3.1`

**Comment by ghiboz** [comment]
so when you press any button of the [0], you can't see which element is pressed, like shows the other

**Comment by Unity-Mihkel** [comment]
Yes

**Comment by ghiboz** [comment]
you have some button pressed? is a convertible to H shifter? I use this http://www.shiftershh.com/ and works fine

**Comment by Unity-Mihkel** [comment]
It's Arcade Game Joystick with micro switches like in this [video](https://www.youtube.com/watch?v=bmYGdOWIVwg)
It only has 2 switches connected and no button is pressed
I disconnected every other controller but still the same.

**Comment by Unity-Mihkel** [comment]
v1.0.12.8 fixed it. Good work.
