### ISSUE TITLE
Issue online

### ISSUE THREAD

**Issue by gRally-Issues** [gRally/dev#588]
# User: Javixk
---
When I entered Test 02 on online rally, after the 2nd stage I clicked to load the 3rd stage but I got and advised "Wrong track loaded" or something like that and now I have 2 times in the 2nd stage and I can't enter the 3rd stage.

### [log](https://www.grally.net/u/uploads/e0220c9961b5d1b4ff18056085fe13b9ac350225.zip)

`v1.0.3.1`

**Comment by ghiboz** [comment]
fided on v1.0.7.8
