### ISSUE TITLE
UI black overlay

### ISSUE THREAD

**Issue by gRally-Issues** [gRally/dev#591]
# User: SyFy
---

#### What happened?
Every time you open the game and move with cursor over the menu they are covered with black squares. They will disappear again if you move cursor over them couple of times
https://youtu.be/O1BkJdhfTIQ
### [log](https://www.grally.net/u/uploads/832c4bd5f149b69c0cbba08f9ee7954d66527209.zip)

`v1.0.3.1`

**Comment by ghiboz** [comment]
same of #495 
please try to add this line in `documents\gRally\gRally.ini`
```ini
[misc]
DisableHardwareAcceleration = true
```

**Comment by Unity-Mihkel** [comment]
Seems ok now with that one true
