### ISSUE TITLE
Game Crash

### ISSUE THREAD

**Issue by gRally-Issues** [gRally/dev#592]
# User: Pelice
---

#### What happened?
game crash

#### Steps to reproduce:
start a live rally stage

#### Considerations...

[crash](https://www.grally.net/u/uploads/bcd4e6154d2b8b42d204afdda29496f3d0146ade.dmp)

[error](https://www.grally.net/u/uploads/99aa9daccaa79f86d2cfeca7da58dce21c701639.log)

### [log](https://www.grally.net/u/uploads/cd172afa4a1e6abdc290bc825e86c8fb1ec9009b.zip)

`v1.0.3.1`

**Comment by ghiboz** [comment]
check the new release with the suggestion helpers
