### ISSUE TITLE
crashes with t500rs

### ISSUE THREAD

**Issue by gRally-Issues** [gRally/dev#597]
# User: Jani Sivonen
---

#### What happened?
Game crashes when i have my t500rs wheel connected when loading to track

#### Steps to reproduce:
wheel connected game crashes when loading, wheel disconnected it works fine

#### Happens one time or always?
always when i have my t500rs wheel connected

#### Considerations...
...
### [log](https://www.grally.net/u/uploads/66a4e0d7c2f4c6af871b425af3df0d0e2ff20f25.zip)

`v1.0.4.7`

**Comment by ghiboz** [comment]
please try to edit `documents\gRally\controls.ini` like this:
```ini
[Steering]
DeviceName = Thrustmaster T500 RS Racing wheel
Device = 0
Type = 0
Item = 0
Fk = 0
Inv = false
Linear = 1
Values = -32768, 32767
Digital = false
WheelAngle = 1050
Goofy = false
```
