### ISSUE TITLE
login failed

### ISSUE THREAD

**Issue by gRally-Issues** [gRally/dev#600]
# User: ?=|DLOVE|=?
---

#### What happened?
Can't start game. Always says "login failed"

#### Steps to reproduce:
Try to start any race and it opens up the game window then says "login failed. check steam connection"

#### Happens one time or always?
always

### [log](https://www.grally.net/u/uploads/7668834067d7fccd93f15f74810b491e2ff097ff.zip)

`v1.0.4.7`

**Comment by ghiboz** [comment]
it's something in your steam username: are you registered on our forum and linked the steam account?
