### ISSUE TITLE
When driving window is open, my steam VR opens too. I have config 1 screen and no VR but still continue the issue. I have to close every times Steam VR or cannot play.

### ISSUE THREAD

**Issue by gRally-Issues** [gRally/dev#603]
# User: HerZak
---

### [log](https://www.grally.net/u/uploads/327ac0149d4984fe616ee99676a5b7a42d202721.zip)

`v1.0.5.4`

**Comment by ghiboz** [comment]
at the moment if you have connected VR, and you want play in monitor mode, you need to power off the vr
