### ISSUE TITLE
"Game crashed" error message after SS3 but game kept running, crashed after SS4

### ISSUE THREAD

**Issue by gRally-Issues** [gRally/dev#604]
# User: cheba
---
After finishing live rally SS3, I got an error message saying game crashed and log files were created. However the game kept running and I could launch SS4. After finishing SS4 and choosing exit, the game crashed to desktop without an error message. After I restart the game, it shows SS4 (Los Marteles 1) as the next stage (even though I already set a time on SS4). If I try to start it, I get a message saying "Error stage choosed" and it launches a different stage (Akagi 2). Even if I run that stage and finish it, it will launch Akagi 2 every time I try to start SS4 (Los Marteles 1).

### [log](https://www.grally.net/u/uploads/c72faafa8e5d878b98fac6a78f050f4f8092e4ea.zip)

`v1.0.5.4`

**Comment by ghiboz** [comment]
fixed in v1.0.6.3
