### ISSUE TITLE
+30s penalty before reaching the start line

### ISSUE THREAD

**Issue by gRally-Issues** [gRally/dev#605]
# User: cheba
---

### [log](https://www.grally.net/u/uploads/f9eff61c44dc2b61a40febdc441062b092e07e3b.zip)

`v1.0.5.4`

**Comment by DjFIL007** [comment]
I've had this occasionally on a few stages too... the distance will say -1.0m (or similar) and it will still penalize me as if I've crossed the line.  Maybe the distance count down needs to be looked at or slightly adjusted on some stage starting areas.
