### ISSUE TITLE
Online Game crash

### ISSUE THREAD

**Issue by khalvador** [gRally/dev#606]
It crashes when I start today rally, stage gArena Jump. 
[error.log](https://github.com/gRally/dev/files/2051316/error.log)

Also, first time, I started from a weird position (see the picture: https://steamuserimages-a.akamaihd.net/ugc/921429632080378914/CC29B3E513974BAFF2B7935ED8874A3D463C0F49/ )

**Comment by ghiboz** [comment]
have you tried another time?

**Comment by ghiboz** [comment]
fixed in v1.0.7.8
