### ISSUE TITLE
Wrong stage loaded

### ISSUE THREAD

**Issue by gRally-Issues** [gRally/dev#608]
# User: kevman_101
---

#### What happened?
In the 24 hour test 01, the 3rd stage that was loaded was Stage 4 and not the Stage 3 Arena Jump like it was suppose to.

### [log](https://www.grally.net/u/uploads/a4adec2bbf29662cd58b8add921637ec07d4b712.zip)

`v1.0.5.4`

**Comment by ghiboz** [comment]
fixed in v1.0.6.3
