### ISSUE TITLE
My Rally of May 29th (crash report)

### ISSUE THREAD

**Issue by DjFIL007** [gRally/dev#609]
First stage... no issues at all.  Second stage... no issues at all.  Third stage (gArena Jump)... works all the way across the finish line, I park my car, and as I choose to exit the stage I get an error resulting in the following crash log.

[Crash_2018-05-29_215218.zip](https://github.com/gRally/dev/files/2052450/Crash_2018-05-29_215218.zip)

Starting Stage 4, will report back.

**Comment by DjFIL007** [comment]
As the sim finishes loading and I see my cockpit view... game has crashed again.  Following crash logs.

[Crash_2018-05-29_220106.zip](https://github.com/gRally/dev/files/2052457/Crash_2018-05-29_220106.zip)

**Comment by DjFIL007** [comment]
I quit gRally to desktop.  Start gRally again, it takes me back to the Live event page, I try to start Stage 4 again... now I get "Error stage choosed"... it has loaded me gArena (w/o jump).  I don't drive, I quit back to gRally menu... get following crash logs.

[Crash_2018-05-29_220514.zip](https://github.com/gRally/dev/files/2052462/Crash_2018-05-29_220514.zip)

**Comment by DjFIL007** [comment]
I can't seem to get past this.  I'll have to withdraw from the rally.  One more log for you.  Hope this helps.

[output_log.txt](https://github.com/gRally/dev/files/2052467/output_log.txt)

**Comment by ghiboz** [comment]
should be fixed in the v1.0.6.3
