### ISSUE TITLE
game freezing and steering wheel setup 

### ISSUE THREAD

**Issue by gRally-Issues** [gRally/dev#610]
# User: imnogoodatthis85
---

#### What happened?
cant get steering wheel to work and game sim crashes or freezes

#### Considerations...

[log](https://www.grally.net/u/uploads/aa4e7730f5e3e5296fd098bf7a528b4b1c8f952f.zip)

### [log](https://www.grally.net/u/uploads/8f9c6ec419bb9dfae31d0a61105a9fc12f96b91d.zip)

`v1.0.5.4`

**Comment by ghiboz** [comment]
edit controls.ini like this:
```ini
[Steering]
DeviceName = Logitech G29 Driving Force Racing Wheel USB
Device = 0
Type = 0
Item = 0
Fk = 0
Inv = false
Linear = 1.03461539745331
Values = -32768, 32767
Digital = false
WheelAngle = 900
Goofy = false

```
