### ISSUE TITLE
Brakes are feel too sharp, I just start pressing brake pedal and my car just starts skidding forward. Maybe I'm the only one.

### ISSUE THREAD

**Issue by gRally-Issues** [gRally/dev#617]
# User: frank
---

### [log](https://www.grally.net/u/uploads/c747d2dbe40d7f8781db7e5fd4f4f462a14f8bff.zip)

`v1.0.6.3`

**Comment by TommyJ1994** [comment]
If you are running on a forestry/gravel stage, make sure you are using Grip/Tarmac tires, as you might get this effect.

**Comment by ghiboz** [comment]
try to change the linearity of the brakes
