### ISSUE TITLE
Online bug

### ISSUE THREAD

**Issue by gRally-Issues** [gRally/dev#619]
# User: Javier
---
I run SS3 normally but when I finished  bug report was done and I was out of the rally. And now I see that the time I got on SS3 is on SS2, so I have two times in SS2.

[dump.live](https://www.grally.net/u/uploads/82089a12c609cf0836ef900820319d08ece4eea1.txt)

### [log](https://www.grally.net/u/uploads/89013ff6597db52b220d6e16d8f893feece2d7b9.zip)

`v1.0.6.3`

**Comment by ghiboz** [comment]
fixed in v1.0.7.8
