### ISSUE TITLE
Crash error after closing stage (Launcher not crashing)

### ISSUE THREAD

**Issue by gRally-Issues** [gRally/dev#621]
# User: Diego
---

#### What happened?
Crash error after closing stage. Not a real problem because the launcher doesn't crash, but annoying.

#### Steps to reproduce:
Closing a stage clicking on the "x" on the bottom left hand side

#### Happens one time or always?
at the moment it has only happened once.

#### Considerations...

[error](https://www.grally.net/u/uploads/3acc6338addea981f1cdbb1101ffcba9fdf5714b.log)

### [log](https://www.grally.net/u/uploads/815834d89f269adefb2b21f282e32e2d49e44f1a.zip)

`v1.0.7.8`

**Comment by Unity-Mihkel** [comment]
Don't know if it is the same issue but for me it's crashing same way almost every time
[error.log](https://github.com/gRally/dev/files/2064306/error.log)

**Comment by ghiboz** [comment]
check the new release with the suggestion helpers
