### ISSUE TITLE
crash after finishing stage 1 in online rally

### ISSUE THREAD

**Issue by gRally-Issues** [gRally/dev#625]
# User: Torwith
---

#### Considerations...

[crash](https://www.grally.net/u/uploads/c2c5cf54669418a8a286dafdbee7727f9d91ae34.dmp)

### [log](https://www.grally.net/u/uploads/c76e9207d63345019c87dda1223bda21dd5442a4.zip)

`v1.0.7.8`

**Comment by ghiboz** [comment]
check the new release with the suggestion helpers
