### ISSUE TITLE
Freeze on start of stage

### ISSUE THREAD

**Issue by gRally-Issues** [gRally/dev#626]
# User: Discopooh
---

#### Considerations...Oculus home keeps starting in the background???

[crash](https://www.grally.net/u/uploads/75b129b58482951468a3d1edd7fc14d4413e65a2.dmp)

[error](https://www.grally.net/u/uploads/82e40a59aab50c7543a3867ecd2fd7414931eaf6.log)

### [log](https://www.grally.net/u/uploads/30d727caf7c279a551d7c557c302e441c3d15418.zip)

`v1.0.7.8`

**Comment by ghiboz** [comment]
check the new release with the suggestion helpers
