### ISSUE TITLE
ONLINE RALLY 24H

### ISSUE THREAD

**Issue by gRally-Issues** [gRally/dev#627]
# User: Tiago Gouveia
---
After SS3, one error in grally 

[Crash_2018-06-02_113600](https://www.grally.net/u/uploads/3789c43e7e7142b1a440cd9686ce0662b0b68044.rar)

### [log](https://www.grally.net/u/uploads/163411ed06c6d9571082f91fb953308163b398b6.zip)

`v1.0.7.8`

**Comment by ghiboz** [comment]
please try to reinstall gRally
