### ISSUE TITLE
crash start grally

### ISSUE THREAD

**Issue by gRally-Issues** [gRally/dev#633]
# User: mariofusti
---

#### Considerations...

![crash grally](https://www.grally.net/u/uploads/086ca7c73b3bfb5832a86f3773f8c741bfd10322.docx)

### [log](https://www.grally.net/u/uploads/79752763942f0e8bf5b676dfc8f9b843dc0a8ff8.zip)

`v1.0.8.7`

**Comment by ghiboz** [comment]
check the new release with the suggestion helpers
