### ISSUE TITLE
Fanatec v2.5 Base NOT WORKING

### ISSUE THREAD

**Issue by gRally-Issues** [gRally/dev#637]
# User: DaNiFLY82
---

#### What happened?
I am trying to assign my Fanatec Gear v2.5 Base, v3 Pedals and SQ v1.5 Shifter in the config menu, but nothing is responding. I can only change the Wheel degress and that's it.  

#### Steps to reproduce:
Fanatec Pedals and Shifter is conected to the Wheel base, I click on the circle to assign and thats it, nothing happens.

#### Happens one time or always?
Since the day of launch I have installed it a few times but it always is the same.

#### Considerations...

![grally](https://www.grally.net/u/uploads/51904c264006735d25f702c176f589474308bb57.jpg)

### [log](https://www.grally.net/u/uploads/36d386e79f080c33d4ff7d2f7e6609af1080fee5.zip)

`v1.0.8.7`

**Comment by DaNiFLY82** [comment]
Is this going to get fixed any time soon? There is a Key that is pressed the whole time -32768. I can't change any inputs, If I unplug the wheel the Keyboard works so it must be a compability issue, can you add the Fanatec v2.5 to the game and make it work, thanks.

**Comment by ghiboz** [comment]
check the new release with the suggestion helpers

**Comment by DaNiFLY82** [comment]
Hi! I have just checked the update but it still does not work. The only thing I can do now is Select the Fanatec Base in the Wheel option, and nothing more. I move the wheel and nothing happens, I can't select Fanatec Base in the pedals and shifter. On all the options available I can see  -32768 like in the photo I submitted.
