### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by gRally-Issues** [gRally/dev#646]
# User: PlAsKus
---

#### What happened?
I started up the gRally "RX" course with the jump, went out through the service area and it crashed on the track.
#### Steps to reproduce:
See "What happened?"
#### Happens one time or always?
I've only tried it once, so i don't know if it was a one time thing.
#### Considerations...
No idea. 
My PC spec is:
Intel Core I7 7700
Asus Prime Z270-P
Ballistix Sport DDR4 16GB 2400 MHz
Asus ROG Strix 1080Ti
Samsung PM961 SSD 512 GB
WD Destop Blue 4TB @5400 RPM

This is the crash report from the TXT file:
gRallySim [version: Unity 2017.4.4f1 (645c9050ba4d)]

mono.dll caused an Access Violation (0xc0000005)
  in module mono.dll at 0033:94a8a1d8.

Error occurred at 2018-06-14_121656.
E:\SteamLibrary\steamapps\common\gRally\gRallySim.exe, run by nicla.
41% memory in use.
16328 MB physical memory [9524 MB free].
18760 MB paging file [7754 MB free].
134217728 MB user address space [134209455 MB free].
Read from location 00000050 caused an access violation.

Context:
RDI:    0x00000008  RSI: 0x00004020  RAX:   0x00000000
RBX:    0xce4d84e0  RCX: 0x00000108  RDX:   0x00000004
RIP:    0x94a8a1d8  RBP: 0x00008000  SegCs: 0x00000033
EFlags: 0x00010202  RSP: 0xe650e950  SegSs: 0x0000002b
R8:    0x94beccd0  R9: 0x00002d38  R10:   0x00000000
R11:    0x00000246  R12: 0x00008000  R13:   0x00000800
R14:    0x00000000  R15: 0x4d837000

Bytes at CS:EIP:
48 8b 44 d0 30 48 d3 e8 83 e0 01 48 83 c4 20 5f 

Stack:
0xe650e950: 3e6e3c60 000001c9 94a89b58 00007ff9 `<n>....X.......
0xe650e960: 00001e6e 00000000 00000001 00000000 n...............
0xe650e970: addd1847 fffffe36 94a8c9aa 00007ff9 G...6...........
0xe650e980: ce4d84e0 000001c9 9494b44e 00007ff9 ..M.....N.......
0xe650e990: 94a875dc 00007ff9 00000000 00000000 .u..............
0xe650e9a0: 3e6e3c60 000001c9 00000000 00000000 `<n>............
0xe650e9b0: 00000000 00000000 94a87bb0 00007ff9 .........{......
0xe650e9c0: 94a875dc 00007ff9 94b949a0 00007ff9 .u.......I......
0xe650e9d0: 00000000 00000000 94a91c9f 00000000 ................
0xe650e9e0: 94a875dc 00007ff9 94a88481 00007ff9 .u..............
0xe650e9f0: 94a875dc 00007ff9 00000000 00000000 .u..............
0xe650ea00: 00000000 00000000 94a91c9f 00000000 ................
0xe650ea10: 0000003c 00000000 94a90430 00007ff9 <.......0.......
0xe650ea20: 0000000a 00000000 00000000 00007ff9 ................
0xe650ea30: 94bac270 00007ff9 94a885fc 00007ff9 p...............
0xe650ea40: 00000001 00000000 94a91c9f 00007ff9 ................
0xe650ea50: 00000000 00000000 94bac270 00007ff9 ........p.......
0xe650ea60: 0000000a 00000000 00010f14 00000000 ................
0xe650ea70: 00000000 00000000 94bac270 00007ff9 ........p.......
0xe650ea80: 0000000a 00000000 94a887c3 00007ff9 ................
0xe650ea90: 0000000a 00000000 00000000 00000000 ................
0xe650eaa0: 00000000 00000000 3ebeba1a 000001c9 ...........>....
0xe650eab0: 0000000a 00000000 94a8710d 00007ff9 .........q......
0xe650eac0: 00000000 00000000 94b949a0 00007ff9 .........I......
0xe650ead0: 0000004a 00000000 4d837000 000001c9 J........p.M....
0xe650eae0: 00000000 00000000 94bab7e0 00007ff9 ................
0xe650eaf0: 0000004a 00000000 94a871ca 00007ff9 J........q......
0xe650eb00: 00000000 00000000 00000011 00000000 ................
0xe650eb10: 00000000 00000000 4d837000 000001c9 .........p.M....
0xe650eb20: 94bab7e0 00007ff9 94a87330 00007ff9 ........0s......
0xe650eb30: 0000004a 00000000 00000011 00000000 J...............
0xe650eb40: 00000000 00000000 0000000a 00000000 ................
0xe650eb50: 00000000 00000000 949aa93a 00007ff9 ........:.......
0xe650eb60: 0000004a 00000000 00000011 00000000 J...............
0xe650eb70: 3e776a00 000001c9 5efa427c 00000000 .jw>....|B.^....
0xe650eb80: 3e776a00 000001c9 3ebd0a4b 000001c9 .jw>....K..>....
0xe650eb90: 5efa427c 00000000 e650ec20 0000007b |B.^.... .P.{...
0xe650eba0: 00000011 00000000 5bbf1b39 00007ff9 ........9..[....
0xe650ebb0: 00000000 00000000 3e5d16d0 000001c9 ..........]>....
0xe650ebc0: 3e5d14e0 000001c9 e650ec10 0000007b ..]>......P.{...
0xe650ebd0: 00000001 00000000 5efa427c 00000000 ........|B.^....
0xe650ebe0: e650ec20 0000007b e650eb90 0000007b  .P.{.....P.{...
0xe650ebf0: 00000000 00000000 00000000 00000000 ................
0xe650ec00: 3e6e3c60 000001c9 4d837000 000001c9 `<n>.....p.M....
0xe650ec10: 00010f24 00000000 00000011 00000000 $...............
0xe650ec20: e650ec80 0000007b 3ebeafdc 000001c9 ..P.{......>....
0xe650ec30: 00000008 00000000 0247388c 00000000 .........8G.....
0xe650ec40: e416241a 00000000 3d6bec08 000001c9 .$........k=....
0xe650ec50: e650ed30 0000007b 5bab8761 00007ff9 0.P.{...a..[....
0xe650ec60: 00000000 00000000 3e6e3c60 000001c9 ........`<n>....
0xe650ec70: 00000011 00000000 00010f24 00000000 ........$.......
0xe650ec80: e650ecd0 0000007b 3ebeaf31 000001c9 ..P.{...1..>....
0xe650ec90: 52839240 000001c9 4da93be8 000001c9 @..R.....;.M....
0xe650eca0: 615aefa0 000001c9 00000433 000001c9 ..Za....3.......
0xe650ecb0: 00000011 00000000 00010f24 00000000 ........$.......
0xe650ecc0: 4d837000 000001c9 00000000 00000000 .p.M............
0xe650ecd0: e650ed20 0000007b 3ebeaec5 000001c9  .P.{......>....
0xe650ece0: 3e6dd280 000001c9 615aefa0 000001c9 ..m>......Za....
0xe650ecf0: e650ed30 0000007b 5bd2a1e9 00007ff9 0.P.{......[....
0xe650ed00: 00000011 00000000 00010f24 00000000 ........$.......
0xe650ed10: 4d837000 000001c9 3e6e3c60 000001c9 .p.M....`<n>....
0xe650ed20: e650edc0 0000007b 3eca3409 000001c9 ..P.{....4.>....
0xe650ed30: e650ed80 0000007b 4da93a40 000001c9 ..P.{...@:.M....
0xe650ed40: 00000000 00000000 00000000 00000000 ................
0xe650ed50: 00000000 00000000 3e5d16d0 000001c9 ..........]>....
0xe650ed60: 3e5d14e0 ad56b868 0000000c 00000000 ..]>h.V.........
0xe650ed70: d699a8cb 00000002 00000000 00000000 ................
0xe650ed80: 52167190 000001c9 3e6dd280 000001c9 .q.R......m>....
0xe650ed90: 59fdc905 00000000 bfacd593 00000000 ...Y............
0xe650eda0: 00000017 00000000 00000002 00000000 ................
0xe650edb0: 3e6f01c0 000001c9 615aefa0 000001c9 ..o>......Za....
0xe650edc0: e650f1f0 0000007b 4da913f6 000001c9 ..P.{......M....
0xe650edd0: bf3504f3 80000000 80000000 3f3504f3 ..5...........5?
0xe650ede0: 00000000 be2a56d3 3eeb2b1a 3f800000 .....V*..+.>...?
0xe650edf0: 42406c6b c4070000 00000000 c0568000 kl@B..........V.
0xe650ee00: 52839330 000001c9 00000000 3ff00000 0..R...........?
0xe650ee10: a0000000 3fe99999 00000000 00000000 .......?........
0xe650ee20: 00000000 40300000 52839270 000001c9 ......0@p..R....
0xe650ee30: 00000020 41a26498 beb2290f bf53df78  ....d.A.)..x.S.
0xe650ee40: bee17b8a 00000000 beb2290f bee17b8b .{.......)...{..
0xe650ee50: 3f53df77 00000000 4408a9a0 4495191a w.S?.......D...D
0xe650ee60: 442a34c2 000001c9 3f800000 3f800000 .4*D.......?...?
0xe650ee70: 3f800000 3f800000 3f6aeaeb 3f590821 ...?...?..j?!.Y?
0xe650ee80: 3f46c344 3f800000 3f6aeaeb 3f590821 D.F?...?..j?!.Y?
0xe650ee90: 3f46c344 3f800000 3f6aeaeb 3f590821 D.F?...?..j?!.Y?
0xe650eea0: 3f46c344 3f800000 beb2290f bf53df78 D.F?...?.)..x.S.
0xe650eeb0: bee17b8a 000001c9 00000000 00000000 .{..............
0xe650eec0: 00000000 00000000 00000000 00000000 ................
0xe650eed0: 00000000 00000000 00000000 00000000 ................
0xe650eee0: 00000000 00000000 41000000 3f800000 ...........A...?
0xe650eef0: 3f4ccccd 3e4ccccc 3ca3d70a 3f800000 ..L?..L>...<...?
0xe650ef00: 3f800000 3f800000 3ebd2a15 000001c9 ...?...?.*.>....
0xe650ef10: 6b5b2d04 00000000 00000000 00000000 .-[k............
0xe650ef20: 00000000 00000000 41800000 00000000 ...........A....
0xe650ef30: 3f4ccccd 3e4ccccc 454b414d 45505f52 ..L?..L>MAKER_PE
0xe650ef40: 49505f52 5f4c4558 3f800000 3f800000 R_PIXEL_...?...?
0xe650ef50: 3f800000 3f800000 3cf5c28f 00000000 ...?...?...<....
0xe650ef60: 00000000 00000000 e650ef10 0000007b ..........P.{...
0xe650ef70: f0d8d850 000001c9 beb2290f bf53df78 P........)..x.S.
0xe650ef80: bee17b8a 000001c9 beb2290f bf53df78 .{.......)..x.S.
0xe650ef90: bee17b8a 00000000 41000000 3f800000 .{.........A...?
0xe650efa0: 3f4ccccd 3e4ccccc bf5f6010 be2a56d3 ..L?..L>.`_..V*.
0xe650efb0: 3eeb2b1a 00007ff9 bf5f6010 be2a56d3 .+.>.....`_..V*.
0xe650efc0: 3eeb2b1a 00000000 beb2290f bee17b8b .+.>.....)...{..
0xe650efd0: 3f53df77 00000000 3ebd5768 3f4e9201 w.S?....hW.>..N?
0xe650efe0: 3eebd097 00007ff9 3ebd5768 3f4e9201 ...>....hW.>..N?
0xe650eff0: 3eebd097 00000000 3f800000 00000000 ...>.......?....
0xe650f000: 00000000 000001c9 bf3504f3 80000000 ..........5.....
0xe650f010: 80000000 3f3504f3 beb2290f bf53df78 ......5?.)..x.S.
0xe650f020: bee17b8a 000001c9 3ca3d70a 3f800000 .{.........<...?
0xe650f030: 3f800000 3f800000 4408a9a0 4495191a ...?...?...D...D
0xe650f040: 442a34c2 000001c9 4408a9a0 4495191a .4*D.......D...D
0xe650f050: 442a34c2 00000000 41800000 00000000 .4*D.......A....
0xe650f060: 3f4ccccd 3e4ccccc 3f800000 3f800000 ..L?..L>...?...?
0xe650f070: 3f800000 3f800000 3eb2290f 3f53df78 ...?...?.).>x.S?
0xe650f080: 3ee17b8a 00000000 3eb2290f 3f53df78 .{.>.....).>x.S?
0xe650f090: 3ee17b8a 00000000 00000020 00000000 .{.>.... .......
0xe650f0a0: 00000020 00000000 bf5f6010 be2a56d3  ........`_..V*.
0xe650f0b0: 3eeb2b1a 0000007b 3f5f6010 3e2a56d3 .+.>{....`_?.V*>
0xe650f0c0: beeb2b1a 000001c9 3f5f6010 3e2a56d3 .+.......`_?.V*>
0xe650f0d0: beeb2b1a 00000000 3f800000 3f800000 .+.........?...?
0xe650f0e0: 3f800000 3f800000 3cf5c28f 00000000 ...?...?...<....
0xe650f0f0: 00000000 00000000 3eb2290f 3ee17b8b .........).>.{.>
0xe650f100: bf53df77 000001c9 3eb2290f 3ee17b8b w.S......).>.{.>
0xe650f110: bf53df77 00000000 3f6aeaeb 3f590821 w.S.......j?!.Y?
0xe650f120: 3f46c344 3f800000 e650f0d0 0000007b D.F?...?..P.{...
0xe650f130: e650f700 0000007b 3e6d4d48 000001c9 ..P.{...HMm>....
0xe650f140: 00000001 00000000 e5a51e45 00000000 ........E.......
0xe650f150: 51ec30d2 00000000 3e6f01c0 000001c9 .0.Q......o>....
0xe650f160: e650f1a0 0000007b 4c66f0ed 000001c9 ..P.{.....fL....
0xe650f170: 00000001 00000000 3e6d4d48 000001c9 ........HMm>....
0xe650f180: e650f700 0000007b 51ec30d2 00000000 ..P.{....0.Q....
0xe650f190: 3e6f01c0 000001c9 52ffd840 000001c9 ..o>....@..R....
0xe650f1a0: e650f1f0 0000007b 4c66efb6 000001c9 ..P.{.....fL....
0xe650f1b0: 52098a88 000001c9 7d519d79 3ca3d70a ...R....y.Q}...<
0xe650f1c0: 523e307e 00000000 00000001 00000000 ~0>R............
0xe650f1d0: 3e6d4d48 000001c9 e650f700 0000007b HMm>......P.{...
0xe650f1e0: 1f2c10fc 00000000 3e6f01c0 000001c9 ..,.......o>....
0xe650f1f0: e650f240 0000007b 4c66ed04 000001c9 @.P.{.....fL....
0xe650f200: e650f240 0000007b 4c5fe4b5 000001c9 @.P.{....._L....
0xe650f210: 00000000 00000000 00000000 00000000 ................
0xe650f220: e5a51e45 00000000 00000001 00000000 E...............
0xe650f230: 51ec30d2 00000000 3e6f01c0 000001c9 .0.Q......o>....
0xe650f240: e650f290 0000007b 4c66d939 000001c9 ..P.{...9.fL....
0xe650f250: e650f290 0000007b 4c66035c 000001c9 ..P.{...\.fL....
0xe650f260: 52998a20 000001c9 3e6d4d48 000001c9  ..R....HMm>....
0xe650f270: 00000000 00000000 e650f620 0000007b ........ .P.{...
0xe650f280: 52098a88 000001c9 3ebf0b50 000001c9 ...R....P..>....
0xe650f290: e650f320 0000007b 3ebf0bbb 000001c9  .P.{......>....
0xe650f2a0: 00000003 00000000 61b51b90 000001c9 ...........a....
0xe650f2b0: 3e7304f0 000001c9 9493232d 00007ff9 ..s>....-#......
0xe650f2c0: e650f750 0000007b 4c66d7c0 000001c9 P.P.{.....fL....
0xe650f2d0: e650f700 0000007b 00000000 00000000 ..P.{...........
0xe650f2e0: 3e6f01c0 000001c9 00000000 00000000 ..o>............
0xe650f2f0: 00000000 00000000 9493228b 00007ff9 ........."......
0xe650f300: 52098a88 000001c9 52098a88 000001c9 ...R.......R....
0xe650f310: 3ebf0b50 000001c9 e650f360 0000007b P..>....`.P.{...
0xe650f320: e650f360 0000007b 94a5651f 00007ff9 `.P.{....e......
0xe650f330: 52098a88 000001c9 00000000 00007ff9 ...R............
0xe650f340: 615aefa0 000001c9 52098a88 000001c9 ..Za.......R....
0xe650f350: 00000000 00000000 9493228b 00007ff9 ........."......
0xe650f360: 3e6d4d48 000001c9 61b5eea8 000001c9 HMm>.......a....
0xe650f370: 3ebd0430 000001c9 615aefa0 000001c9 0..>......Za....
0xe650f380: 3e7304f0 000001c9 3e6f01c0 000001c9 ..s>......o>....
0xe650f390: e650f700 0000007b e650f620 0000007b ..P.{... .P.{...
0xe650f3a0: 61b51b10 000001c9 61b5eea8 000001c9 ...a.......a....
0xe650f3b0: 493122b0 000001c9 00000000 000001c9 ."1I............
0xe650f3c0: 3e6d4d48 000001c9 493122b0 000001c9 HMm>....."1I....
0xe650f3d0: 5179cabd 000003b2 61b51b10 000001c9 ..yQ.......a....
0xe650f3e0: 3e7304f0 000001c9 00000000 00000000 ..s>............
0xe650f3f0: e650f780 0000007b e650f6a0 0000007b ..P.{.....P.{...
0xe650f400: 3e7304f0 000001c9 00000000 00000000 ..s>............
0xe650f410: e650f780 0000007b e650f6a0 0000007b ..P.{.....P.{...
0xe650f420: 00000000 00000000 949a8a51 00007ff9 ........Q.......
0xe650f430: e650f584 0000007b 00000003 00000000 ..P.{...........
0xe650f440: e650f590 0000007b 0000001d 000001c9 ..P.{...........
0xe650f450: 00000000 00000000 5bcbb784 00007ff9 ...........[....
0xe650f460: 60d8bb80 000001c9 e650f970 0000007b ...`....p.P.{...
0xe650f470: e650f4d0 0000007b 0040480f 00000000 ..P.{....H@.....
0xe650f480: e650f5f0 0000007b 5bcb5cd0 00007ff9 ..P.{....\.[....
0xe650f490: e650f758 0000007b e650f750 0000007b X.P.{...P.P.{...
0xe650f4a0: 5179cb4d 000003b2 00000000 00000000 M.yQ............
0xe650f4b0: e650f750 0000007b 00000000 00000000 P.P.{...........
0xe650f4c0: 00000000 00000000 00000001 00000000 ................
0xe650f4d0: 00000000 00000000 e650f700 0000007b ..........P.{...
0xe650f4e0: e650f620 0000007b 52098a88 000001c9  .P.{......R....
0xe650f4f0: 3e6f01c0 000001c9 949a8a49 00007ff9 ..o>....I.......
0xe650f500: 5179cbed 000003b2 00000000 00000000 ..yQ............
0xe650f510: 00000000 00000000 00000000 00000000 ................
0xe650f520: 3e6f01c0 000001c9 5bcbb784 00007ff9 ..o>.......[....
0xe650f530: 52098a88 000001c9 e650f770 0000007b ...R....p.P.{...
0xe650f540: e650f5a0 0000007b 61b5eea8 000001c9 ..P.{......a....
0xe650f550: e650f5c0 0000007b 5bcb5cd0 00007ff9 ..P.{....\.[....
0xe650f560: e650f710 0000007b e650f700 0000007b ..P.{.....P.{...
0xe650f570: 00000000 00000000 949a8a51 00007ff9 ........Q.......
0xe650f580: e650f700 0000007b 5bcbb700 00007ff9 ..P.{......[....
0xe650f590: 63aeae40 000001c9 5bc99219 00007ff9 @..c.......[....
0xe650f5a0: 63aeae40 000001c9 52098a88 000001c9 @..c.......R....
0xe650f5b0: 00000000 00000000 5bcb5cd0 00007ff9 .........\.[....
0xe650f5c0: 3e4cccc8 00000000 00000000 00000000 ..L>............
0xe650f5d0: 3f4cccce 00000000 00000000 00000000 ..L?............
0xe650f5e0: 00000000 00000000 5b90a970 00007ff9 ........p..[....
0xe650f5f0: 4244e5bf 000001c9 4244e5bf 00007ff9 ..DB......DB....
0xe650f600: 40e08322 00000000 00000000 00000000 "..@............
0xe650f610: 3e5f0618 3e112c2e 40e05bb1 00000000 .._>.,.>.[.@....
0xe650f620: 00000000 00000000 00000000 00000000 ................
0xe650f630: 00000000 00000000 00000000 00000000 ................
0xe650f640: 00000000 00000000 00000000 00000000 ................
0xe650f650: 00000000 00000000 00000000 00000000 ................
0xe650f660: 00000000 00000000 00000000 00000000 ................
0xe650f670: 00000000 00000000 00000000 00000000 ................
0xe650f680: 00000000 00000000 00000000 00000000 ................
0xe650f690: 00000000 00000000 00000000 00000000 ................
0xe650f6a0: 41a26498 00000000 00000000 00000000 .d.A............
0xe650f6b0: 00000000 40344c93 52098a88 000001c9 .....L4@...R....
0xe650f6c0: 3e6f01c0 000001c9 00000000 00000000 ..o>............
0xe650f6d0: 0000217e 00000000 00000000 00000000 ~!..............
0xe650f6e0: 00000000 00000000 5c130101 00007ff9 ...........\....
0xe650f6f0: 00000000 00000000 5bc993b0 00007ff9 ...........[....
0xe650f700: 00000000 00000000 63aeae40 000001c9 ........@..c....
0xe650f710: 00000000 00000000 5bb68fbe 00007ff9 ...........[....
0xe650f720: 3c87a4b0 000001c9 5ba62f50 00007ff9 ...<....P/.[....
0xe650f730: 3e6f01c0 000001c9 3cbd2890 000001c9 ..o>.....(.<....
0xe650f740: 00000a7c 00000000 5bba2f49 00007ff9 |.......I/.[....
0xe650f750: 2d63d500 000001c9 63afcdc0 000001c9 ..c-.......c....
0xe650f760: 3cb0f770 000001c9 63aeaed0 000001c9 p..<.......c....
0xe650f770: e650f970 0000007b 5bba4565 00007ff9 p.P.{...eE.[....
0xe650f780: 00000001 00000000 00000a7c 00000000 ........|.......
0xe650f790: 00000000 00000000 e650f970 0000007b ........p.P.{...
0xe650f7a0: 5bb0c750 000001c9 e650f830 0000007b P..[....0.P.{...
0xe650f7b0: 0000eef8 ff004000 02fb0915 0a5309cc .....@........S.
0xe650f7c0: 00000001 00000000 5c141544 00007ff9 ........D..\....
0xe650f7d0: 00000a7c 00000000 00000000 00000000 |...............
0xe650f7e0: 00000001 00000000 e650f970 0000007b ........p.P.{...
0xe650f7f0: 00000000 00000000 5c14093a 00007ff9 ........:..\....
0xe650f800: 00000a7c 00000000 e650f970 0000007b |.......p.P.{...
0xe650f810: 00000001 00000000 00000000 00000000 ................
0xe650f820: 00000001 00000000 0000000b 00000000 ................
0xe650f830: 000c0fe4 00000000 000014fe 00000000 ................
0xe650f840: 138911bc 00000000 00000001 00000000 ................
0xe650f850: 0013c874 000003bf 000002f4 00000000 t...............
0xe650f860: 00000700 00000000 5c142ecc 00007ff9 ...........\....
0xe650f870: 00000001 00000000 e650f970 0000007b ........p.P.{...
0xe650f880: 00000001 00000000 00000001 00000000 ................
0xe650f890: 00000000 00000000 00000000 000001c9 ................
0xe650f8a0: 0000001d 00000000 e650f9a0 0000007b ..........P.{...
0xe650f8b0: 00000000 00000000 65646968 646e6957 ........hideWind
0xe650f8c0: 0000776f 005c0065 0000000a 00000000 ow..e.\.........
0xe650f8d0: 00000044 006b0073 00000000 00000000 D...s.k.........
0xe650f8e0: 65726170 5748746e 0000444e 00610065 parentHWND..e.a.
0xe650f8f0: 0000000a 00000000 00000044 00790072 ........D...r.y.
0xe650f900: 3c884b80 000001c9 3c884ba8 000001c9 .K.<.....K.<....
0xe650f910: 3c884ba8 000001c9 00650074 006d0061 .K.<....t.e.a.m.
0xe650f920: 0069004c 00720062 00720061 005c0079 L.i.b.r.a.r.y.\.
0xe650f930: 00740073 00610065 0061006d 00700070 s.t.e.a.m.a.p.p.
0xe650f940: 3c87f650 000001c9 0000003e 00000000 P..<....>.......
0xe650f950: 0067005c 00610052 0000003e 00000000 \.g.R.a.>.......
0xe650f960: 00000044 006c0061 3c87f610 000001c9 D...a.l....<....
0xe650f970: 00000036 00000000 00000065 0000007b 6.......e...{...
0xe650f980: 00000036 00000000 00000044 00000000 6.......D.......
0xe650f990: 00000000 00000000 6c615267 6953796c ........gRallySi
0xe650f9a0: 7265006d 00000000 00000009 00000000 m.er............
0xe650f9b0: 00000044 00000000 3c87a750 000001c9 D.......P..<....
0xe650f9c0: 00000012 00000000 ac972b55 00007ff9 ........U+......
0xe650f9d0: 0000000a 00000000 00000044 00007ff9 ........D.......
0xe650f9e0: 00000000 00000000 3c87f5d0 000001c9 ...........<....
0xe650f9f0: 0000003b 00000000 e650fa00 0000007b ;.........P.{...
0xe650fa00: 0000003b 00000000 00000044 00007ff9 ;.......D.......
0xe650fa10: 3c867c70 000001c9 00000051 00000000 p|.<....Q.......
0xe650fa20: 00000000 00000000 00000051 00000000 ........Q.......
0xe650fa30: 00000044 00000000 0000004c 00000000 D.......L.......
0xe650fa40: 0000183c 00000000 00000000 00000000 <...............
0xe650fa50: 3b5742a0 000001c9 23b1b288 00007ff7 .BW;.......#....
0xe650fa60: 3c86f670 000001c9 00000040 00000000 p..<....@.......
0xe650fa70: 23b248e0 00007ff7 0000003f 00000000 .H.#....?.......
0xe650fa80: 00000044 00000000 3c86f6c0 000001c9 D..........<....
0xe650fa90: 00000043 00000000 23b1198e 00007ff7 C..........#....
0xe650faa0: 00000043 00000000 00000044 00007ff7 C.......D.......
0xe650fab0: 00000fa0 00000000 00000000 00000000 ................
0xe650fac0: 00000068 00000000 39632f92 000001c9 h......../c9....
0xe650fad0: 39632f72 000001c9 39632f06 000001c9 r/c9...../c9....
0xe650fae0: 00000000 00000000 00000000 00000000 ................
0xe650faf0: 00000000 00000000 00000000 00000000 ................
0xe650fb00: 00000000 00000000 5c1430bb 00007ff9 .........0.\....
0xe650fb10: 00000001 00000000 00000000 00000000 ................
0xe650fb20: 00000000 00000000 23b176a4 00007ff7 .........v.#....
0xe650fb30: 00000001 00000000 23b113ee 00007ff7 ...........#....
0xe650fb40: 00000000 00000000 23b25bf8 00007ff7 .........[.#....
0xe650fb50: 00000000 00000000 00000000 00000000 ................
0xe650fb60: 00000000 00000000 00000000 00000000 ................
0xe650fb70: 00000000 00000000 ac223034 00007ff9 ........40".....
0xe650fb80: 00000000 00000000 00000000 00000000 ................
0xe650fb90: 00000000 00000000 00000000 00000000 ................
0xe650fba0: 00000000 00000000 ac9d1431 00007ff9 ........1.......
0xe650fbb0: 00000000 00000000 00000000 00000000 ................
0xe650fbc0: 00000000 00000000 e650fbd0 0000007b ..........P.{...
0xe650fbd0: 00000000 00000000 a92bbf10 00007ff9 ..........+.....
0xe650fbe0: e650da50 0000007b e650da50 0000007b P.P.{...P.P.{...
0xe650fbf0: 00000202 00000000 00000000 00000000 ................
0xe650fc00: 00000000 00000000 00000000 00000000 ................
0xe650fc10: 00000000 00000000 00000000 00000000 ................
0xe650fc20: 00000000 00000000 00000000 00000000 ................
0xe650fc30: 00000000 00000000 00000000 00000000 ................
0xe650fc40: 00000000 00000000 00000000 00000000 ................
0xe650fc50: 00000000 00000000 00000000 00000000 ................
0xe650fc60: 00000000 00000000 00000000 00000000 ................
0xe650fc70: 00000000 00000000 00000000 00000000 ................
0xe650fc80: 00000000 00000000 00000000 00000000 ................
0xe650fc90: 00000000 00000000 00000000 00000000 ................
0xe650fca0: 00000000 00000000 00000000 00000000 ................
0xe650fcb0: 00000000 00000000 00000000 00000000 ................
0xe650fcc0: 00000000 00000000 00000000 00000000 ................
0xe650fcd0: 00000000 00000000 00000000 00000000 ................
0xe650fce0: 00000000 00000000 00000000 00000000 ................
0xe650fcf0: 00000000 00000000 00000000 00000000 ................
0xe650fd00: 00000000 00000000 00000000 00000000 ................
0xe650fd10: 00000000 00000000 00000000 00000000 ................
0xe650fd20: 00000000 00000000 00000000 00000000 ................
0xe650fd30: 00000000 00000000 00000000 00000000 ................
0xe650fd40: 00000000 00000000 00000000 00000000 ................
0xe650fd50: 00000000 00000000 00000000 00000000 ................
0xe650fd60: 00000000 00000000 00000000 00000000 ................
0xe650fd70: 00000000 00000000 00000000 00000000 ................
0xe650fd80: 00000000 00000000 00000000 00000000 ................
0xe650fd90: 00000000 00000000 00000000 00000000 ................
0xe650fda0: 00000000 00000000 00000000 00000000 ................
0xe650fdb0: 00000000 00000000 00000000 00000000 ................
0xe650fdc0: 00000000 00000000 00000000 00000000 ................
0xe650fdd0: 00000000 00000000 00000000 00000000 ................
0xe650fde0: 00000000 00000000 00000000 00000000 ................
0xe650fdf0: 00000000 00000000 00000000 00000000 ................
0xe650fe00: 00000000 00000000 00000000 00000000 ................
0xe650fe10: 00000000 00000000 00000000 00000000 ................
0xe650fe20: 00000000 00000000 00000000 00000000 ................
0xe650fe30: 00000000 00000000 00000000 00000000 ................
0xe650fe40: 00000000 00000000 00000000 00000000 ................
0xe650fe50: 00000000 00000000 00000000 00000000 ................
0xe650fe60: 00000000 00000000 00000000 00000000 ................
0xe650fe70: 00000000 00000000 00000000 00000000 ................
0xe650fe80: 00000000 00000000 00000000 00000000 ................
0xe650fe90: 00000000 00000000 00000000 00000000 ................
0xe650fea0: 00000000 00000000 00000000 00000000 ................
0xe650feb0: 00000000 00000000 00000000 00000000 ................
0xe650fec0: 00000000 00000000 00000000 00000000 ................
0xe650fed0: 00000000 00000000 00000000 00000000 ................
0xe650fee0: 00000000 00000000 00000000 00000000 ................
0xe650fef0: 00000000 00000000 00000000 00000000 ................
0xe650ff00: 00000000 00000000 00000000 00000000 ................
0xe650ff10: 00000000 00000000 00000000 00000000 ................
0xe650ff20: 00000000 00000000 00000000 00000000 ................
0xe650ff30: 00000000 00000000 00000000 00000000 ................
0xe650ff40: 00000000 00000000 00000000 00000000 ................
0xe650ff50: 00000000 00000000 00000000 00000000 ................
0xe650ff60: 00000000 00000000 00000000 00000000 ................
0xe650ff70: 00000000 00000000 00000000 00000000 ................
0xe650ff80: 00000000 00000000 00000000 00000000 ................
0xe650ff90: 00000000 00000000 00000000 00000000 ................
0xe650ffa0: 00000000 00000000 00000000 00000000 ................
0xe650ffb0: 00000000 00000000 00000000 00000000 ................
0xe650ffc0: 00000000 00000000 00000000 00000000 ................
0xe650ffd0: 00000000 00000000 00000000 00000000 ................
0xe650ffe0: 00000000 00000000 00000000 00000000 ................
0xe650fff0: 00000000 00000000 00000000 00000000 ................

Module 1
C:\WINDOWS\SYSTEM32\xinput1_3.dll
Image Base: 0x00400000  Image Size: 0x0001e000
File Size:  107368      File Time:  2007-04-04_195422
Version:
   Company:    Microsoft Corporation
   Product:    Microsoft® DirectX for Windows®
   FileDesc:   Microsoft Common Controller API
   FileVer:    9.18.944.0
   ProdVer:    9.18.944.0

Module 2
C:\Program Files (x86)\Steam\steamclient64.dll
Image Base: 0x66490000  Image Size: 0x00e47000
File Size:  14726208    File Time:  2018-06-09_013906
Version:
   Company:    Valve Corporation
   Product:    Steam
   FileDesc:   Steamclient.dll
   FileVer:    4.55.34.56
   ProdVer:    3.0.0.1

Module 3
E:\SteamLibrary\steamapps\common\gRally\steam_api64.dll
Image Base: 0x672e0000  Image Size: 0x00041000
File Size:  250656      File Time:  2018-06-01_090138
Version:
   Company:    Valve Corporation
   Product:    Steam Client API
   FileDesc:   Steam Client API
   FileVer:    4.28.51.7
   ProdVer:    1.0.0.1

Module 4
C:\Program Files (x86)\Steam\vstdlib_s64.dll
Image Base: 0x67cd0000  Image Size: 0x00079000
File Size:  477984      File Time:  2018-06-09_013922
Version:
   Company:    Valve Corporation
   Product:    Steam
   FileDesc:   vstdlib_ s.dll
   FileVer:    4.55.34.56
   ProdVer:    3.0.0.1

Module 5
C:\Program Files (x86)\Steam\tier0_s64.dll
Image Base: 0x67d50000  Image Size: 0x00172000
File Size:  379168      File Time:  2018-06-09_013908
Version:
   Company:    Valve Corporation
   Product:     tier0_s Dynamic Link Library
   FileDesc:   tier0_s Dynamic Link Library
   FileVer:    4.55.34.56
   ProdVer:    1.0.0.1

Module 6
E:\SteamLibrary\steamapps\common\gRally\gRallySim_Data\Plugins\steam_api64.dll
Image Base: 0x67ed0000  Image Size: 0x00041000
File Size:  250656      File Time:  2018-06-01_090138
Version:
   Company:    Valve Corporation
   Product:    Steam Client API
   FileDesc:   Steam Client API
   FileVer:    4.28.51.7
   ProdVer:    1.0.0.1

== [end of error.log] ==
### [log](https://www.grally.net/u/uploads/f63ddccef51dbe7f0a82f1a20b347071bbaead73.zip)

`v1.0.9.7`

**Comment by ghiboz** [comment]
check the new release with the suggestion helpers
