### ISSUE TITLE
Crash after quitting a stage

### ISSUE THREAD

**Issue by gRally-Issues** [gRally/dev#647]
# User: cheba
---
I paused and quit in the middle of a stage, got a message that the game has crashed and logs had been created. Crashed to main menu only, not to Windows.

### [log](https://www.grally.net/u/uploads/3db38880eb087c4bb57b8ac8df33a706de265f24.zip)

`v1.0.9.7`

**Comment by ghiboz** [comment]
check the new release with the suggestion helpers
