### ISSUE TITLE
Steering wheel Thrustmaster T300 bad calibration

### ISSUE THREAD

**Issue by gRally-Issues** [gRally/dev#649]
# User: akiruo
---

#### What happened?
Thrustmaster T300 is recognized, but when the game starts, the steering is not calibrated. In the settings everything is OK. The steering wheel is set to 540 degrees rotation.
#### Happens one time or always?
It happens all the time. As soon as I change the settings, it becomes worse. The baddest situation was that I turned 1 or 2 degrees and the car responded with 180 degrees.
### [log](https://www.grally.net/u/uploads/ff826aa00bed0934eb48305a5f7378c87952f146.zip)

`v1.0.9.7`

**Comment by ghiboz** [comment]
check the new release with the suggestion helpers
