### ISSUE TITLE
Crash on loading drive mode

### ISSUE THREAD

**Issue by gRally-Issues** [gRally/dev#650]
# User: [ITA]ZephirPFS47
---

#### What happened?
it keep crashing when i try to drive, happens on every track
#### Steps to reproduce:
-Press drive button
-Wait until it end saying 01 build physic
#### Happens one time or always
always
#### Considerations...
It started doing that just after i entered the form where to choose livery, i changed color of the name and exited
[error](https://www.grally.net/u/uploads/32af8e33bc8ac7fb5a28fa9b1d0c84b955ec65e7.log)

[error](https://www.grally.net/u/uploads/6aa4059fe2da077f9eb1f2f94a06cbdb82d2f5bd.log)

[error](https://www.grally.net/u/uploads/87e1d3feb5626f86ebf816b6e4e55d61f86eccce.log)

etc...

### [log](https://www.grally.net/u/uploads/618cc928202b06f68c5bfebf913bc4d60ea1366d.zip)

`v1.0.9.7`

**Comment by ghiboz** [comment]
check the new release with the suggestion helpers
