### ISSUE TITLE
'Drive' section crashes after enable H-shifter.

### ISSUE THREAD

**Issue by gRally-Issues** [gRally/dev#652]
# User: Willy Brake
---

#### What happened?
Had game configured to G920 padded shift, with external H shifter 4th gear configured as handbrake and all was well.
Then switched on H shifter and now code crashes when press Drive icon.
Went back into Config and change handbrake to a G920 button as thought maybe a clash between handbrake and H shifter, but game still crashes.

#### Steps to reproduce:
See above

#### Happens one time or always?
Havent tried restarting the entire game yet, after changing the handbrake.

#### Considerations...
Liking the game BUT I get no feedback through the G920 wheel on tyre grip. It is a complete guess when the grip will go.  I get collision feedback OK and dirt sections vibrate the wheel.  Also I feel the curbs BUT only when I reverse over them and not when mount them when cutting a corner.  Please fix as a priority as without tyre grip feedback this game loses its purpose. 

Regards
Gary Raymond 

### [log](https://www.grally.net/u/uploads/836da90c6b6a6b82c61b2e653ec6609ee6349287.zip)

`v1.0.9.7`

**Comment by ghiboz** [comment]
check the new release with the suggestion helpers
