### ISSUE TITLE
Crash on loading

### ISSUE THREAD

**Issue by gRally-Issues** [gRally/dev#654]
# User: [ITA]ZephirPFS47
---

#### What happened?

When i press drive button, it load everything and when there is written Sim ready it crashes

#### Steps to reproduce:

Press drive button with every car and track

#### Happens one time or always?

always

#### Considerations...

[crash](https://www.grally.net/u/uploads/102a2cc941ade0800ae490296124c4fd00c75f4f.dmp)

[error](https://www.grally.net/u/uploads/10d33628ac3b7eebac827750f8e9a9aac48b48f0.log)

### [log](https://www.grally.net/u/uploads/325c6fb9ac28b14d8802d128c12afc2ea956382b.zip)

`v1.0.10.2`

**Comment by ghiboz** [comment]
check the new release with the suggestion helpers
