### ISSUE TITLE
Steering Wheel Wont Center Correctly

### ISSUE THREAD

**Issue by gRally-Issues** [gRally/dev#666]
# User: tofufrazier
---

#### What happened?

Steering Wheel (Logitech G29) wont center correctly.  The configuration settings won't show the wheel input going to the right at all.  Only the left and even then the full input range won't display.

#### Happens one time or always?

Always

### [log](https://www.grally.net/u/uploads/7360a6f013529737ec98c62b609f477e5bfd67e6.zip)

`v1.0.12.8`

**Comment by ghiboz** [comment]
please
 1. check `use analog steer`
 2. click the button and move the wheel to be detected
 3. set the wheel angle

![](https://i.imgur.com/d0EgZ0P.png)
