### ISSUE TITLE
Issue with my trustmaster tr500

### ISSUE THREAD

**Issue by gRally-Issues** [gRally/dev#670]
# User: Jassport
---

#### What happened?
The game doesn't recognize my Thrustmaster tr500. It doesn't appear anything on the copnfiguration menu.
#### Steps to reproduce:
When I try to configurate my wheel it doesn't appear. 
#### Happens one time or always?
It happens always. 
#### Considerations...
Is the trustmaster tr500 accepted for this game or what?? 
Please send me instructions.
### [log](https://www.grally.net/u/uploads/5d5cf46e72b011e6136d40b80012e605d126e45d.zip)

`v1.0.12.8`

**Comment by ghiboz** [comment]
fixed in v1.0.13.12
