### ISSUE TITLE
Had One Time Issue With Uploading to Github from in-game.

### ISSUE THREAD

**Issue by gRally-Issues** [gRally/dev#682]
# User: DjFIL007
---

#### What happened?
was trying to upload logs and other issue (first attempt with screenshot attached) and it failed to progress, but was locked at the upload screen.

#### Steps to reproduce:
unknown

#### Happens one time or always?
was able to reproduce twice, but then when i exited program and restarted it it allowed me to submit this report.

#### Considerations...
none

### [log](https://www.grally.net/u/uploads/7b366071931b0296b52b3a408f16188d4f52cb56.zip)

`v1.0.16.18`

**Comment by DjFIL007** [comment]
Appears quitting the program and restarting the program has allowed me to upload to github, unsure why but 2-3 times I was unable to (submit button locked, had to go off issues tab, and then back.

**Comment by DjFIL007** [comment]
other related note, would prefer if leaving the issues tab and returning to it (such as to check game settings/preferences) would save any partial info for issue while being written.

**Comment by ghiboz** [comment]
will be done in the next release
