### ISSUE TITLE
Black Skybox on Seprate Render

### ISSUE THREAD

**Issue by DjFIL007** [gRally/dev#683]
![20181226225026_1](https://user-images.githubusercontent.com/14816160/50469906-5f7dc100-0963-11e9-9205-13baf571e9a5.jpg)
[log.zip](https://github.com/gRally/dev/files/2711739/log.zip)

When separate render is enabled, black skybox on left/right monitors... middle monitor is fine.  tested on garena and dragons tail.

**Comment by ghiboz** [comment]
fixed in the next release:
![](https://i.imgur.com/al4QJ7W.png)
