### ISSUE TITLE
Wheel only senses right half of rotation

### ISSUE THREAD

**Issue by Millicant** [gRally/dev#695]
What is happening:
- In game: Center on physical wheel is full left rotation in-game.  Of the wheel's 900 degrees of rotation, only the right 450 is used.  So center on wheel is full left in game, full right on wheel is full right in game.  Rotation is not linear (ie wheel does not match in-game wheel). 
- In settings/controls: wheel reacts normally.  Set to "analog" and gRally senses full rotation with center at true physical center.  

Repeatable: 
Yes, every time.  No escaping it!  Sadly it's making the game unplayable right now.  

Notes:
Fanatec CSW v2.5.  Works normally in other programs - not a hardware/software issue with device.

**Comment by ghiboz** [comment]
hi @Millicant can you send me your *****.controls.ini** file located in `documents\gRally folder?`

**Comment by Millicant** [comment]
Here you are sir! There are two, I saved them separately trying to solve it.  

[Millicant Controls.zip](https://github.com/gRally/dev/files/4719717/Millicant.Controls.zip)

**Comment by ghiboz** [comment]
[Controls.controls.zip](https://github.com/gRally/dev/files/4719735/Controls.controls.zip)
can you try with this file?

thanks for your patience

**Comment by Millicant** [comment]
That worked!

What was I doing wrong?
