### ISSUE TITLE
Cannot start live rally

### ISSUE THREAD

**Issue by gRally** [gRally/dev#697]
# User: [ITA]ZephirPFS47
---

#### What happened?
When i click drive it ask me to choose a setup but i cannot choose it cause it's greyed out. Also the only drive button is on the second stage not the first one
#### Steps to reproduce:
Go to live, join a championship, click drive
#### Happens one time or always?
Always, i tried to restart the game and cleared steam cache

![20201202150811_1](https://www.grally.net/u/uploads/93c90b1702de402d2f644b6edbb17b6ec9970f2a.jpg)

![20201202150811_1](https://www.grally.net/u/uploads/93c90b1702de402d2f644b6edbb17b6ec9970f2a.jpg)

![20201202150816_1](https://www.grally.net/u/uploads/daba82e09ed4c892345d92ee794285e8f9f128b1.jpg)

### [log](https://www.grally.net/u/uploads/2f49636c2dc861c9f99ea6b2996fdcd61494f635.zip)

`v1.1.4.7`

**Comment by ghiboz** [comment]
strange behaviour,
I restored your set, you're able to partecipate
let me know
